// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: context_player_options.proto

package spotify.player.proto;

public final class ContextPlayerOptionsOuterClass {
    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_spotify_player_proto_ContextPlayerOptions_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_spotify_player_proto_ContextPlayerOptions_fieldAccessorTable;
    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_spotify_player_proto_ContextPlayerOptionOverrides_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_spotify_player_proto_ContextPlayerOptionOverrides_fieldAccessorTable;
    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static {
        java.lang.String[] descriptorData = {
                "\n\034context_player_options.proto\022\024spotify." +
                        "player.proto\"e\n\024ContextPlayerOptions\022\031\n\021" +
                        "shuffling_context\030\001 \001(\010\022\031\n\021repeating_con" +
                        "text\030\002 \001(\010\022\027\n\017repeating_track\030\003 \001(\010\"m\n\034C" +
                        "ontextPlayerOptionOverrides\022\031\n\021shuffling" +
                        "_context\030\001 \001(\010\022\031\n\021repeating_context\030\002 \001(" +
                        "\010\022\027\n\017repeating_track\030\003 \001(\010B\002H\002"
        };
        com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
                new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
                    public com.google.protobuf.ExtensionRegistry assignDescriptors(
                            com.google.protobuf.Descriptors.FileDescriptor root) {
                        descriptor = root;
                        return null;
                    }
                };
        com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{
                        }, assigner);
        internal_static_spotify_player_proto_ContextPlayerOptions_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_spotify_player_proto_ContextPlayerOptions_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_spotify_player_proto_ContextPlayerOptions_descriptor,
                new java.lang.String[]{"ShufflingContext", "RepeatingContext", "RepeatingTrack",});
        internal_static_spotify_player_proto_ContextPlayerOptionOverrides_descriptor =
                getDescriptor().getMessageTypes().get(1);
        internal_static_spotify_player_proto_ContextPlayerOptionOverrides_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_spotify_player_proto_ContextPlayerOptionOverrides_descriptor,
                new java.lang.String[]{"ShufflingContext", "RepeatingContext", "RepeatingTrack",});
    }

    private ContextPlayerOptionsOuterClass() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }

    public interface ContextPlayerOptionsOrBuilder extends
            // @@protoc_insertion_point(interface_extends:spotify.player.proto.ContextPlayerOptions)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>optional bool shuffling_context = 1;</code>
         */
        boolean hasShufflingContext();

        /**
         * <code>optional bool shuffling_context = 1;</code>
         */
        boolean getShufflingContext();

        /**
         * <code>optional bool repeating_context = 2;</code>
         */
        boolean hasRepeatingContext();

        /**
         * <code>optional bool repeating_context = 2;</code>
         */
        boolean getRepeatingContext();

        /**
         * <code>optional bool repeating_track = 3;</code>
         */
        boolean hasRepeatingTrack();

        /**
         * <code>optional bool repeating_track = 3;</code>
         */
        boolean getRepeatingTrack();
    }

    public interface ContextPlayerOptionOverridesOrBuilder extends
            // @@protoc_insertion_point(interface_extends:spotify.player.proto.ContextPlayerOptionOverrides)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>optional bool shuffling_context = 1;</code>
         */
        boolean hasShufflingContext();

        /**
         * <code>optional bool shuffling_context = 1;</code>
         */
        boolean getShufflingContext();

        /**
         * <code>optional bool repeating_context = 2;</code>
         */
        boolean hasRepeatingContext();

        /**
         * <code>optional bool repeating_context = 2;</code>
         */
        boolean getRepeatingContext();

        /**
         * <code>optional bool repeating_track = 3;</code>
         */
        boolean hasRepeatingTrack();

        /**
         * <code>optional bool repeating_track = 3;</code>
         */
        boolean getRepeatingTrack();
    }

    /**
     * Protobuf type {@code spotify.player.proto.ContextPlayerOptions}
     */
    public static final class ContextPlayerOptions extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:spotify.player.proto.ContextPlayerOptions)
            ContextPlayerOptionsOrBuilder {
        public static final int SHUFFLING_CONTEXT_FIELD_NUMBER = 1;
        public static final int REPEATING_CONTEXT_FIELD_NUMBER = 2;
        public static final int REPEATING_TRACK_FIELD_NUMBER = 3;
        private static final long serialVersionUID = 0L;
        // @@protoc_insertion_point(class_scope:spotify.player.proto.ContextPlayerOptions)
        private static final spotify.player.proto.ContextPlayerOptionsOuterClass.ContextPlayerOptions DEFAULT_INSTANCE;
        @java.lang.Deprecated
        public static final com.google.protobuf.Parser<ContextPlayerOptions>
                PARSER = new com.google.protobuf.AbstractParser<ContextPlayerOptions>() {
            @java.lang.Override
            public ContextPlayerOptions parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                Builder builder = newBuilder();
                try {
                    builder.mergeFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    throw e.setUnfinishedMessage(builder.buildPartial());
                } catch (java.io.IOException e) {
                    throw new com.google.protobuf.InvalidProtocolBufferException(
                            e.getMessage()).setUnfinishedMessage(
                            builder.buildPartial());
                }
                return builder.buildPartial();
            }
        };

        static {
            DEFAULT_INSTANCE = new spotify.player.proto.ContextPlayerOptionsOuterClass.ContextPlayerOptions();
        }

        private int bitField0_;
        private boolean shufflingContext_;
        private boolean repeatingContext_;
        private boolean repeatingTrack_;

        // Use ContextPlayerOptions.newBuilder() to construct.
        private ContextPlayerOptions(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }

        private ContextPlayerOptions() {
            shufflingContext_ = false;
            repeatingContext_ = false;
            repeatingTrack_ = false;
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return spotify.player.proto.ContextPlayerOptionsOuterClass.internal_static_spotify_player_proto_ContextPlayerOptions_descriptor;
        }

        public static spotify.player.proto.ContextPlayerOptionsOuterClass.ContextPlayerOptions parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static spotify.player.proto.ContextPlayerOptionsOuterClass.ContextPlayerOptions parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static spotify.player.proto.ContextPlayerOptionsOuterClass.ContextPlayerOptions parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static spotify.player.proto.ContextPlayerOptionsOuterClass.ContextPlayerOptions parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static spotify.player.proto.ContextPlayerOptionsOuterClass.ContextPlayerOptions parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static spotify.player.proto.ContextPlayerOptionsOuterClass.ContextPlayerOptions parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static spotify.player.proto.ContextPlayerOptionsOuterClass.ContextPlayerOptions parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static spotify.player.proto.ContextPlayerOptionsOuterClass.ContextPlayerOptions parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static spotify.player.proto.ContextPlayerOptionsOuterClass.ContextPlayerOptions parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }

        public static spotify.player.proto.ContextPlayerOptionsOuterClass.ContextPlayerOptions parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static spotify.player.proto.ContextPlayerOptionsOuterClass.ContextPlayerOptions parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static spotify.player.proto.ContextPlayerOptionsOuterClass.ContextPlayerOptions parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(spotify.player.proto.ContextPlayerOptionsOuterClass.ContextPlayerOptions prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        public static spotify.player.proto.ContextPlayerOptionsOuterClass.ContextPlayerOptions getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        public static com.google.protobuf.Parser<ContextPlayerOptions> parser() {
            return PARSER;
        }

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return this.unknownFields;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return spotify.player.proto.ContextPlayerOptionsOuterClass.internal_static_spotify_player_proto_ContextPlayerOptions_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            spotify.player.proto.ContextPlayerOptionsOuterClass.ContextPlayerOptions.class, spotify.player.proto.ContextPlayerOptionsOuterClass.ContextPlayerOptions.Builder.class);
        }

        /**
         * <code>optional bool shuffling_context = 1;</code>
         */
        public boolean hasShufflingContext() {
            return ((bitField0_ & 0x00000001) == 0x00000001);
        }

        /**
         * <code>optional bool shuffling_context = 1;</code>
         */
        public boolean getShufflingContext() {
            return shufflingContext_;
        }

        /**
         * <code>optional bool repeating_context = 2;</code>
         */
        public boolean hasRepeatingContext() {
            return ((bitField0_ & 0x00000002) == 0x00000002);
        }

        /**
         * <code>optional bool repeating_context = 2;</code>
         */
        public boolean getRepeatingContext() {
            return repeatingContext_;
        }

        /**
         * <code>optional bool repeating_track = 3;</code>
         */
        public boolean hasRepeatingTrack() {
            return ((bitField0_ & 0x00000004) == 0x00000004);
        }

        /**
         * <code>optional bool repeating_track = 3;</code>
         */
        public boolean getRepeatingTrack() {
            return repeatingTrack_;
        }

        @java.lang.Override
        public Builder newBuilderForType() {
            return newBuilder();
        }

        @java.lang.Override
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<ContextPlayerOptions> getParserForType() {
            return PARSER;
        }

        @java.lang.Override
        public spotify.player.proto.ContextPlayerOptionsOuterClass.ContextPlayerOptions getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

        /**
         * Protobuf type {@code spotify.player.proto.ContextPlayerOptions}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:spotify.player.proto.ContextPlayerOptions)
                spotify.player.proto.ContextPlayerOptionsOuterClass.ContextPlayerOptionsOrBuilder {
            private int bitField0_;
            private boolean shufflingContext_;
            private boolean repeatingContext_;
            private boolean repeatingTrack_;

            // Construct using spotify.player.proto.ContextPlayerOptionsOuterClass.ContextPlayerOptions.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return spotify.player.proto.ContextPlayerOptionsOuterClass.internal_static_spotify_player_proto_ContextPlayerOptions_descriptor;
            }

            @java.lang.Override
            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return spotify.player.proto.ContextPlayerOptionsOuterClass.internal_static_spotify_player_proto_ContextPlayerOptions_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                spotify.player.proto.ContextPlayerOptionsOuterClass.ContextPlayerOptions.class, spotify.player.proto.ContextPlayerOptionsOuterClass.ContextPlayerOptions.Builder.class);
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                }
            }

            @java.lang.Override
            public Builder clear() {
                super.clear();
                shufflingContext_ = false;
                bitField0_ = (bitField0_ & ~0x00000001);
                repeatingContext_ = false;
                bitField0_ = (bitField0_ & ~0x00000002);
                repeatingTrack_ = false;
                bitField0_ = (bitField0_ & ~0x00000004);
                return this;
            }

            @java.lang.Override
            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return spotify.player.proto.ContextPlayerOptionsOuterClass.internal_static_spotify_player_proto_ContextPlayerOptions_descriptor;
            }

            @java.lang.Override
            public spotify.player.proto.ContextPlayerOptionsOuterClass.ContextPlayerOptions getDefaultInstanceForType() {
                return spotify.player.proto.ContextPlayerOptionsOuterClass.ContextPlayerOptions.getDefaultInstance();
            }

            @java.lang.Override
            public spotify.player.proto.ContextPlayerOptionsOuterClass.ContextPlayerOptions build() {
                spotify.player.proto.ContextPlayerOptionsOuterClass.ContextPlayerOptions result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @java.lang.Override
            public spotify.player.proto.ContextPlayerOptionsOuterClass.ContextPlayerOptions buildPartial() {
                spotify.player.proto.ContextPlayerOptionsOuterClass.ContextPlayerOptions result = new spotify.player.proto.ContextPlayerOptionsOuterClass.ContextPlayerOptions(this);
                int from_bitField0_ = bitField0_;
                int to_bitField0_ = 0;
                if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
                    to_bitField0_ |= 0x00000001;
                }
                result.shufflingContext_ = shufflingContext_;
                if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
                    to_bitField0_ |= 0x00000002;
                }
                result.repeatingContext_ = repeatingContext_;
                if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
                    to_bitField0_ |= 0x00000004;
                }
                result.repeatingTrack_ = repeatingTrack_;
                result.bitField0_ = to_bitField0_;
                onBuilt();
                return result;
            }

            @java.lang.Override
            public Builder clone() {
                return super.clone();
            }

            @java.lang.Override
            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return super.setField(field, value);
            }

            @java.lang.Override
            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return super.clearField(field);
            }

            @java.lang.Override
            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return super.clearOneof(oneof);
            }

            @java.lang.Override
            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, java.lang.Object value) {
                return super.setRepeatedField(field, index, value);
            }

            @java.lang.Override
            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return super.addRepeatedField(field, value);
            }

            /**
             * <code>optional bool shuffling_context = 1;</code>
             */
            public boolean hasShufflingContext() {
                return ((bitField0_ & 0x00000001) == 0x00000001);
            }

            /**
             * <code>optional bool shuffling_context = 1;</code>
             */
            public boolean getShufflingContext() {
                return shufflingContext_;
            }

            /**
             * <code>optional bool shuffling_context = 1;</code>
             */
            public Builder setShufflingContext(boolean value) {
                bitField0_ |= 0x00000001;
                shufflingContext_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional bool shuffling_context = 1;</code>
             */
            public Builder clearShufflingContext() {
                bitField0_ = (bitField0_ & ~0x00000001);
                shufflingContext_ = false;
                onChanged();
                return this;
            }

            /**
             * <code>optional bool repeating_context = 2;</code>
             */
            public boolean hasRepeatingContext() {
                return ((bitField0_ & 0x00000002) == 0x00000002);
            }

            /**
             * <code>optional bool repeating_context = 2;</code>
             */
            public boolean getRepeatingContext() {
                return repeatingContext_;
            }

            /**
             * <code>optional bool repeating_context = 2;</code>
             */
            public Builder setRepeatingContext(boolean value) {
                bitField0_ |= 0x00000002;
                repeatingContext_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional bool repeating_context = 2;</code>
             */
            public Builder clearRepeatingContext() {
                bitField0_ = (bitField0_ & ~0x00000002);
                repeatingContext_ = false;
                onChanged();
                return this;
            }

            /**
             * <code>optional bool repeating_track = 3;</code>
             */
            public boolean hasRepeatingTrack() {
                return ((bitField0_ & 0x00000004) == 0x00000004);
            }

            /**
             * <code>optional bool repeating_track = 3;</code>
             */
            public boolean getRepeatingTrack() {
                return repeatingTrack_;
            }

            /**
             * <code>optional bool repeating_track = 3;</code>
             */
            public Builder setRepeatingTrack(boolean value) {
                bitField0_ |= 0x00000004;
                repeatingTrack_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional bool repeating_track = 3;</code>
             */
            public Builder clearRepeatingTrack() {
                bitField0_ = (bitField0_ & ~0x00000004);
                repeatingTrack_ = false;
                onChanged();
                return this;
            }

            @java.lang.Override
            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.setUnknownFields(unknownFields);
            }

            @java.lang.Override
            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.mergeUnknownFields(unknownFields);
            }


            // @@protoc_insertion_point(builder_scope:spotify.player.proto.ContextPlayerOptions)
        }

    }

    /**
     * Protobuf type {@code spotify.player.proto.ContextPlayerOptionOverrides}
     */
    public static final class ContextPlayerOptionOverrides extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:spotify.player.proto.ContextPlayerOptionOverrides)
            ContextPlayerOptionOverridesOrBuilder {
        public static final int SHUFFLING_CONTEXT_FIELD_NUMBER = 1;
        public static final int REPEATING_CONTEXT_FIELD_NUMBER = 2;
        public static final int REPEATING_TRACK_FIELD_NUMBER = 3;
        private static final long serialVersionUID = 0L;
        // @@protoc_insertion_point(class_scope:spotify.player.proto.ContextPlayerOptionOverrides)
        private static final spotify.player.proto.ContextPlayerOptionsOuterClass.ContextPlayerOptionOverrides DEFAULT_INSTANCE;
        @java.lang.Deprecated
        public static final com.google.protobuf.Parser<ContextPlayerOptionOverrides>
                PARSER = new com.google.protobuf.AbstractParser<ContextPlayerOptionOverrides>() {
            @java.lang.Override
            public ContextPlayerOptionOverrides parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                Builder builder = newBuilder();
                try {
                    builder.mergeFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    throw e.setUnfinishedMessage(builder.buildPartial());
                } catch (java.io.IOException e) {
                    throw new com.google.protobuf.InvalidProtocolBufferException(
                            e.getMessage()).setUnfinishedMessage(
                            builder.buildPartial());
                }
                return builder.buildPartial();
            }
        };

        static {
            DEFAULT_INSTANCE = new spotify.player.proto.ContextPlayerOptionsOuterClass.ContextPlayerOptionOverrides();
        }

        private int bitField0_;
        private boolean shufflingContext_;
        private boolean repeatingContext_;
        private boolean repeatingTrack_;

        // Use ContextPlayerOptionOverrides.newBuilder() to construct.
        private ContextPlayerOptionOverrides(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }

        private ContextPlayerOptionOverrides() {
            shufflingContext_ = false;
            repeatingContext_ = false;
            repeatingTrack_ = false;
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return spotify.player.proto.ContextPlayerOptionsOuterClass.internal_static_spotify_player_proto_ContextPlayerOptionOverrides_descriptor;
        }

        public static spotify.player.proto.ContextPlayerOptionsOuterClass.ContextPlayerOptionOverrides parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static spotify.player.proto.ContextPlayerOptionsOuterClass.ContextPlayerOptionOverrides parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static spotify.player.proto.ContextPlayerOptionsOuterClass.ContextPlayerOptionOverrides parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static spotify.player.proto.ContextPlayerOptionsOuterClass.ContextPlayerOptionOverrides parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static spotify.player.proto.ContextPlayerOptionsOuterClass.ContextPlayerOptionOverrides parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static spotify.player.proto.ContextPlayerOptionsOuterClass.ContextPlayerOptionOverrides parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static spotify.player.proto.ContextPlayerOptionsOuterClass.ContextPlayerOptionOverrides parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static spotify.player.proto.ContextPlayerOptionsOuterClass.ContextPlayerOptionOverrides parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static spotify.player.proto.ContextPlayerOptionsOuterClass.ContextPlayerOptionOverrides parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }

        public static spotify.player.proto.ContextPlayerOptionsOuterClass.ContextPlayerOptionOverrides parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static spotify.player.proto.ContextPlayerOptionsOuterClass.ContextPlayerOptionOverrides parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static spotify.player.proto.ContextPlayerOptionsOuterClass.ContextPlayerOptionOverrides parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(spotify.player.proto.ContextPlayerOptionsOuterClass.ContextPlayerOptionOverrides prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        public static spotify.player.proto.ContextPlayerOptionsOuterClass.ContextPlayerOptionOverrides getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        public static com.google.protobuf.Parser<ContextPlayerOptionOverrides> parser() {
            return PARSER;
        }

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return this.unknownFields;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return spotify.player.proto.ContextPlayerOptionsOuterClass.internal_static_spotify_player_proto_ContextPlayerOptionOverrides_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            spotify.player.proto.ContextPlayerOptionsOuterClass.ContextPlayerOptionOverrides.class, spotify.player.proto.ContextPlayerOptionsOuterClass.ContextPlayerOptionOverrides.Builder.class);
        }

        /**
         * <code>optional bool shuffling_context = 1;</code>
         */
        public boolean hasShufflingContext() {
            return ((bitField0_ & 0x00000001) == 0x00000001);
        }

        /**
         * <code>optional bool shuffling_context = 1;</code>
         */
        public boolean getShufflingContext() {
            return shufflingContext_;
        }

        /**
         * <code>optional bool repeating_context = 2;</code>
         */
        public boolean hasRepeatingContext() {
            return ((bitField0_ & 0x00000002) == 0x00000002);
        }

        /**
         * <code>optional bool repeating_context = 2;</code>
         */
        public boolean getRepeatingContext() {
            return repeatingContext_;
        }

        /**
         * <code>optional bool repeating_track = 3;</code>
         */
        public boolean hasRepeatingTrack() {
            return ((bitField0_ & 0x00000004) == 0x00000004);
        }

        /**
         * <code>optional bool repeating_track = 3;</code>
         */
        public boolean getRepeatingTrack() {
            return repeatingTrack_;
        }

        @java.lang.Override
        public Builder newBuilderForType() {
            return newBuilder();
        }

        @java.lang.Override
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<ContextPlayerOptionOverrides> getParserForType() {
            return PARSER;
        }

        @java.lang.Override
        public spotify.player.proto.ContextPlayerOptionsOuterClass.ContextPlayerOptionOverrides getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

        /**
         * Protobuf type {@code spotify.player.proto.ContextPlayerOptionOverrides}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:spotify.player.proto.ContextPlayerOptionOverrides)
                spotify.player.proto.ContextPlayerOptionsOuterClass.ContextPlayerOptionOverridesOrBuilder {
            private int bitField0_;
            private boolean shufflingContext_;
            private boolean repeatingContext_;
            private boolean repeatingTrack_;

            // Construct using spotify.player.proto.ContextPlayerOptionsOuterClass.ContextPlayerOptionOverrides.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return spotify.player.proto.ContextPlayerOptionsOuterClass.internal_static_spotify_player_proto_ContextPlayerOptionOverrides_descriptor;
            }

            @java.lang.Override
            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return spotify.player.proto.ContextPlayerOptionsOuterClass.internal_static_spotify_player_proto_ContextPlayerOptionOverrides_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                spotify.player.proto.ContextPlayerOptionsOuterClass.ContextPlayerOptionOverrides.class, spotify.player.proto.ContextPlayerOptionsOuterClass.ContextPlayerOptionOverrides.Builder.class);
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                }
            }

            @java.lang.Override
            public Builder clear() {
                super.clear();
                shufflingContext_ = false;
                bitField0_ = (bitField0_ & ~0x00000001);
                repeatingContext_ = false;
                bitField0_ = (bitField0_ & ~0x00000002);
                repeatingTrack_ = false;
                bitField0_ = (bitField0_ & ~0x00000004);
                return this;
            }

            @java.lang.Override
            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return spotify.player.proto.ContextPlayerOptionsOuterClass.internal_static_spotify_player_proto_ContextPlayerOptionOverrides_descriptor;
            }

            @java.lang.Override
            public spotify.player.proto.ContextPlayerOptionsOuterClass.ContextPlayerOptionOverrides getDefaultInstanceForType() {
                return spotify.player.proto.ContextPlayerOptionsOuterClass.ContextPlayerOptionOverrides.getDefaultInstance();
            }

            @java.lang.Override
            public spotify.player.proto.ContextPlayerOptionsOuterClass.ContextPlayerOptionOverrides build() {
                spotify.player.proto.ContextPlayerOptionsOuterClass.ContextPlayerOptionOverrides result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @java.lang.Override
            public spotify.player.proto.ContextPlayerOptionsOuterClass.ContextPlayerOptionOverrides buildPartial() {
                spotify.player.proto.ContextPlayerOptionsOuterClass.ContextPlayerOptionOverrides result = new spotify.player.proto.ContextPlayerOptionsOuterClass.ContextPlayerOptionOverrides(this);
                int from_bitField0_ = bitField0_;
                int to_bitField0_ = 0;
                if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
                    to_bitField0_ |= 0x00000001;
                }
                result.shufflingContext_ = shufflingContext_;
                if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
                    to_bitField0_ |= 0x00000002;
                }
                result.repeatingContext_ = repeatingContext_;
                if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
                    to_bitField0_ |= 0x00000004;
                }
                result.repeatingTrack_ = repeatingTrack_;
                result.bitField0_ = to_bitField0_;
                onBuilt();
                return result;
            }

            @java.lang.Override
            public Builder clone() {
                return super.clone();
            }

            @java.lang.Override
            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return super.setField(field, value);
            }

            @java.lang.Override
            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return super.clearField(field);
            }

            @java.lang.Override
            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return super.clearOneof(oneof);
            }

            @java.lang.Override
            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, java.lang.Object value) {
                return super.setRepeatedField(field, index, value);
            }

            @java.lang.Override
            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return super.addRepeatedField(field, value);
            }

            /**
             * <code>optional bool shuffling_context = 1;</code>
             */
            public boolean hasShufflingContext() {
                return ((bitField0_ & 0x00000001) == 0x00000001);
            }

            /**
             * <code>optional bool shuffling_context = 1;</code>
             */
            public boolean getShufflingContext() {
                return shufflingContext_;
            }

            /**
             * <code>optional bool shuffling_context = 1;</code>
             */
            public Builder setShufflingContext(boolean value) {
                bitField0_ |= 0x00000001;
                shufflingContext_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional bool shuffling_context = 1;</code>
             */
            public Builder clearShufflingContext() {
                bitField0_ = (bitField0_ & ~0x00000001);
                shufflingContext_ = false;
                onChanged();
                return this;
            }

            /**
             * <code>optional bool repeating_context = 2;</code>
             */
            public boolean hasRepeatingContext() {
                return ((bitField0_ & 0x00000002) == 0x00000002);
            }

            /**
             * <code>optional bool repeating_context = 2;</code>
             */
            public boolean getRepeatingContext() {
                return repeatingContext_;
            }

            /**
             * <code>optional bool repeating_context = 2;</code>
             */
            public Builder setRepeatingContext(boolean value) {
                bitField0_ |= 0x00000002;
                repeatingContext_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional bool repeating_context = 2;</code>
             */
            public Builder clearRepeatingContext() {
                bitField0_ = (bitField0_ & ~0x00000002);
                repeatingContext_ = false;
                onChanged();
                return this;
            }

            /**
             * <code>optional bool repeating_track = 3;</code>
             */
            public boolean hasRepeatingTrack() {
                return ((bitField0_ & 0x00000004) == 0x00000004);
            }

            /**
             * <code>optional bool repeating_track = 3;</code>
             */
            public boolean getRepeatingTrack() {
                return repeatingTrack_;
            }

            /**
             * <code>optional bool repeating_track = 3;</code>
             */
            public Builder setRepeatingTrack(boolean value) {
                bitField0_ |= 0x00000004;
                repeatingTrack_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional bool repeating_track = 3;</code>
             */
            public Builder clearRepeatingTrack() {
                bitField0_ = (bitField0_ & ~0x00000004);
                repeatingTrack_ = false;
                onChanged();
                return this;
            }

            @java.lang.Override
            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.setUnknownFields(unknownFields);
            }

            @java.lang.Override
            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.mergeUnknownFields(unknownFields);
            }


            // @@protoc_insertion_point(builder_scope:spotify.player.proto.ContextPlayerOptionOverrides)
        }

    }

    // @@protoc_insertion_point(outer_class_scope)
}
