// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: play_origin.proto

package spotify.player.proto;

public final class PlayOriginOuterClass {
    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_spotify_player_proto_PlayOrigin_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_spotify_player_proto_PlayOrigin_fieldAccessorTable;
    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static {
        java.lang.String[] descriptorData = {
                "\n\021play_origin.proto\022\024spotify.player.prot" +
                        "o\"\277\001\n\nPlayOrigin\022\032\n\022feature_identifier\030\001" +
                        " \001(\t\022\027\n\017feature_version\030\002 \001(\t\022\020\n\010view_ur" +
                        "i\030\003 \001(\t\022\031\n\021external_referrer\030\004 \001(\t\022\033\n\023re" +
                        "ferrer_identifier\030\005 \001(\t\022\031\n\021device_identi" +
                        "fier\030\006 \001(\t\022\027\n\017feature_classes\030\007 \003(\tB\002H\002"
        };
        com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
                new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
                    public com.google.protobuf.ExtensionRegistry assignDescriptors(
                            com.google.protobuf.Descriptors.FileDescriptor root) {
                        descriptor = root;
                        return null;
                    }
                };
        com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{
                        }, assigner);
        internal_static_spotify_player_proto_PlayOrigin_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_spotify_player_proto_PlayOrigin_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_spotify_player_proto_PlayOrigin_descriptor,
                new java.lang.String[]{"FeatureIdentifier", "FeatureVersion", "ViewUri", "ExternalReferrer", "ReferrerIdentifier", "DeviceIdentifier", "FeatureClasses",});
    }

    private PlayOriginOuterClass() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }

    public interface PlayOriginOrBuilder extends
            // @@protoc_insertion_point(interface_extends:spotify.player.proto.PlayOrigin)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>optional string feature_identifier = 1;</code>
         */
        boolean hasFeatureIdentifier();

        /**
         * <code>optional string feature_identifier = 1;</code>
         */
        java.lang.String getFeatureIdentifier();

        /**
         * <code>optional string feature_identifier = 1;</code>
         */
        com.google.protobuf.ByteString
        getFeatureIdentifierBytes();

        /**
         * <code>optional string feature_version = 2;</code>
         */
        boolean hasFeatureVersion();

        /**
         * <code>optional string feature_version = 2;</code>
         */
        java.lang.String getFeatureVersion();

        /**
         * <code>optional string feature_version = 2;</code>
         */
        com.google.protobuf.ByteString
        getFeatureVersionBytes();

        /**
         * <code>optional string view_uri = 3;</code>
         */
        boolean hasViewUri();

        /**
         * <code>optional string view_uri = 3;</code>
         */
        java.lang.String getViewUri();

        /**
         * <code>optional string view_uri = 3;</code>
         */
        com.google.protobuf.ByteString
        getViewUriBytes();

        /**
         * <code>optional string external_referrer = 4;</code>
         */
        boolean hasExternalReferrer();

        /**
         * <code>optional string external_referrer = 4;</code>
         */
        java.lang.String getExternalReferrer();

        /**
         * <code>optional string external_referrer = 4;</code>
         */
        com.google.protobuf.ByteString
        getExternalReferrerBytes();

        /**
         * <code>optional string referrer_identifier = 5;</code>
         */
        boolean hasReferrerIdentifier();

        /**
         * <code>optional string referrer_identifier = 5;</code>
         */
        java.lang.String getReferrerIdentifier();

        /**
         * <code>optional string referrer_identifier = 5;</code>
         */
        com.google.protobuf.ByteString
        getReferrerIdentifierBytes();

        /**
         * <code>optional string device_identifier = 6;</code>
         */
        boolean hasDeviceIdentifier();

        /**
         * <code>optional string device_identifier = 6;</code>
         */
        java.lang.String getDeviceIdentifier();

        /**
         * <code>optional string device_identifier = 6;</code>
         */
        com.google.protobuf.ByteString
        getDeviceIdentifierBytes();

        /**
         * <code>repeated string feature_classes = 7;</code>
         */
        java.util.List<java.lang.String>
        getFeatureClassesList();

        /**
         * <code>repeated string feature_classes = 7;</code>
         */
        int getFeatureClassesCount();

        /**
         * <code>repeated string feature_classes = 7;</code>
         */
        java.lang.String getFeatureClasses(int index);

        /**
         * <code>repeated string feature_classes = 7;</code>
         */
        com.google.protobuf.ByteString
        getFeatureClassesBytes(int index);
    }

    /**
     * Protobuf type {@code spotify.player.proto.PlayOrigin}
     */
    public static final class PlayOrigin extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:spotify.player.proto.PlayOrigin)
            PlayOriginOrBuilder {
        public static final int FEATURE_IDENTIFIER_FIELD_NUMBER = 1;
        public static final int FEATURE_VERSION_FIELD_NUMBER = 2;
        public static final int VIEW_URI_FIELD_NUMBER = 3;
        public static final int EXTERNAL_REFERRER_FIELD_NUMBER = 4;
        public static final int REFERRER_IDENTIFIER_FIELD_NUMBER = 5;
        public static final int DEVICE_IDENTIFIER_FIELD_NUMBER = 6;
        public static final int FEATURE_CLASSES_FIELD_NUMBER = 7;
        private static final long serialVersionUID = 0L;
        // @@protoc_insertion_point(class_scope:spotify.player.proto.PlayOrigin)
        private static final spotify.player.proto.PlayOriginOuterClass.PlayOrigin DEFAULT_INSTANCE;
        @java.lang.Deprecated
        public static final com.google.protobuf.Parser<PlayOrigin>
                PARSER = new com.google.protobuf.AbstractParser<PlayOrigin>() {
            @java.lang.Override
            public PlayOrigin parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                Builder builder = newBuilder();
                try {
                    builder.mergeFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    throw e.setUnfinishedMessage(builder.buildPartial());
                } catch (java.io.IOException e) {
                    throw new com.google.protobuf.InvalidProtocolBufferException(
                            e.getMessage()).setUnfinishedMessage(
                            builder.buildPartial());
                }
                return builder.buildPartial();
            }
        };

        static {
            DEFAULT_INSTANCE = new spotify.player.proto.PlayOriginOuterClass.PlayOrigin();
        }

        private int bitField0_;
        private volatile java.lang.Object featureIdentifier_;
        private volatile java.lang.Object featureVersion_;
        private volatile java.lang.Object viewUri_;
        private volatile java.lang.Object externalReferrer_;
        private volatile java.lang.Object referrerIdentifier_;
        private volatile java.lang.Object deviceIdentifier_;
        private com.google.protobuf.LazyStringList featureClasses_;

        // Use PlayOrigin.newBuilder() to construct.
        private PlayOrigin(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }

        private PlayOrigin() {
            featureIdentifier_ = "";
            featureVersion_ = "";
            viewUri_ = "";
            externalReferrer_ = "";
            referrerIdentifier_ = "";
            deviceIdentifier_ = "";
            featureClasses_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return spotify.player.proto.PlayOriginOuterClass.internal_static_spotify_player_proto_PlayOrigin_descriptor;
        }

        public static spotify.player.proto.PlayOriginOuterClass.PlayOrigin parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static spotify.player.proto.PlayOriginOuterClass.PlayOrigin parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static spotify.player.proto.PlayOriginOuterClass.PlayOrigin parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static spotify.player.proto.PlayOriginOuterClass.PlayOrigin parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static spotify.player.proto.PlayOriginOuterClass.PlayOrigin parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static spotify.player.proto.PlayOriginOuterClass.PlayOrigin parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static spotify.player.proto.PlayOriginOuterClass.PlayOrigin parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static spotify.player.proto.PlayOriginOuterClass.PlayOrigin parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static spotify.player.proto.PlayOriginOuterClass.PlayOrigin parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }

        public static spotify.player.proto.PlayOriginOuterClass.PlayOrigin parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static spotify.player.proto.PlayOriginOuterClass.PlayOrigin parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static spotify.player.proto.PlayOriginOuterClass.PlayOrigin parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(spotify.player.proto.PlayOriginOuterClass.PlayOrigin prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        public static spotify.player.proto.PlayOriginOuterClass.PlayOrigin getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        public static com.google.protobuf.Parser<PlayOrigin> parser() {
            return PARSER;
        }

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return this.unknownFields;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return spotify.player.proto.PlayOriginOuterClass.internal_static_spotify_player_proto_PlayOrigin_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            spotify.player.proto.PlayOriginOuterClass.PlayOrigin.class, spotify.player.proto.PlayOriginOuterClass.PlayOrigin.Builder.class);
        }

        /**
         * <code>optional string feature_identifier = 1;</code>
         */
        public boolean hasFeatureIdentifier() {
            return ((bitField0_ & 0x00000001) == 0x00000001);
        }

        /**
         * <code>optional string feature_identifier = 1;</code>
         */
        public java.lang.String getFeatureIdentifier() {
            java.lang.Object ref = featureIdentifier_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                if (bs.isValidUtf8()) {
                    featureIdentifier_ = s;
                }
                return s;
            }
        }

        /**
         * <code>optional string feature_identifier = 1;</code>
         */
        public com.google.protobuf.ByteString
        getFeatureIdentifierBytes() {
            java.lang.Object ref = featureIdentifier_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                featureIdentifier_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>optional string feature_version = 2;</code>
         */
        public boolean hasFeatureVersion() {
            return ((bitField0_ & 0x00000002) == 0x00000002);
        }

        /**
         * <code>optional string feature_version = 2;</code>
         */
        public java.lang.String getFeatureVersion() {
            java.lang.Object ref = featureVersion_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                if (bs.isValidUtf8()) {
                    featureVersion_ = s;
                }
                return s;
            }
        }

        /**
         * <code>optional string feature_version = 2;</code>
         */
        public com.google.protobuf.ByteString
        getFeatureVersionBytes() {
            java.lang.Object ref = featureVersion_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                featureVersion_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>optional string view_uri = 3;</code>
         */
        public boolean hasViewUri() {
            return ((bitField0_ & 0x00000004) == 0x00000004);
        }

        /**
         * <code>optional string view_uri = 3;</code>
         */
        public java.lang.String getViewUri() {
            java.lang.Object ref = viewUri_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                if (bs.isValidUtf8()) {
                    viewUri_ = s;
                }
                return s;
            }
        }

        /**
         * <code>optional string view_uri = 3;</code>
         */
        public com.google.protobuf.ByteString
        getViewUriBytes() {
            java.lang.Object ref = viewUri_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                viewUri_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>optional string external_referrer = 4;</code>
         */
        public boolean hasExternalReferrer() {
            return ((bitField0_ & 0x00000008) == 0x00000008);
        }

        /**
         * <code>optional string external_referrer = 4;</code>
         */
        public java.lang.String getExternalReferrer() {
            java.lang.Object ref = externalReferrer_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                if (bs.isValidUtf8()) {
                    externalReferrer_ = s;
                }
                return s;
            }
        }

        /**
         * <code>optional string external_referrer = 4;</code>
         */
        public com.google.protobuf.ByteString
        getExternalReferrerBytes() {
            java.lang.Object ref = externalReferrer_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                externalReferrer_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>optional string referrer_identifier = 5;</code>
         */
        public boolean hasReferrerIdentifier() {
            return ((bitField0_ & 0x00000010) == 0x00000010);
        }

        /**
         * <code>optional string referrer_identifier = 5;</code>
         */
        public java.lang.String getReferrerIdentifier() {
            java.lang.Object ref = referrerIdentifier_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                if (bs.isValidUtf8()) {
                    referrerIdentifier_ = s;
                }
                return s;
            }
        }

        /**
         * <code>optional string referrer_identifier = 5;</code>
         */
        public com.google.protobuf.ByteString
        getReferrerIdentifierBytes() {
            java.lang.Object ref = referrerIdentifier_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                referrerIdentifier_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>optional string device_identifier = 6;</code>
         */
        public boolean hasDeviceIdentifier() {
            return ((bitField0_ & 0x00000020) == 0x00000020);
        }

        /**
         * <code>optional string device_identifier = 6;</code>
         */
        public java.lang.String getDeviceIdentifier() {
            java.lang.Object ref = deviceIdentifier_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                if (bs.isValidUtf8()) {
                    deviceIdentifier_ = s;
                }
                return s;
            }
        }

        /**
         * <code>optional string device_identifier = 6;</code>
         */
        public com.google.protobuf.ByteString
        getDeviceIdentifierBytes() {
            java.lang.Object ref = deviceIdentifier_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                deviceIdentifier_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>repeated string feature_classes = 7;</code>
         */
        public com.google.protobuf.ProtocolStringList
        getFeatureClassesList() {
            return featureClasses_;
        }

        /**
         * <code>repeated string feature_classes = 7;</code>
         */
        public int getFeatureClassesCount() {
            return featureClasses_.size();
        }

        /**
         * <code>repeated string feature_classes = 7;</code>
         */
        public java.lang.String getFeatureClasses(int index) {
            return featureClasses_.get(index);
        }

        /**
         * <code>repeated string feature_classes = 7;</code>
         */
        public com.google.protobuf.ByteString
        getFeatureClassesBytes(int index) {
            return featureClasses_.getByteString(index);
        }

        @java.lang.Override
        public Builder newBuilderForType() {
            return newBuilder();
        }

        @java.lang.Override
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<PlayOrigin> getParserForType() {
            return PARSER;
        }

        @java.lang.Override
        public spotify.player.proto.PlayOriginOuterClass.PlayOrigin getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

        /**
         * Protobuf type {@code spotify.player.proto.PlayOrigin}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:spotify.player.proto.PlayOrigin)
                spotify.player.proto.PlayOriginOuterClass.PlayOriginOrBuilder {
            private int bitField0_;
            private java.lang.Object featureIdentifier_ = "";
            private java.lang.Object featureVersion_ = "";
            private java.lang.Object viewUri_ = "";
            private java.lang.Object externalReferrer_ = "";
            private java.lang.Object referrerIdentifier_ = "";
            private java.lang.Object deviceIdentifier_ = "";
            private com.google.protobuf.LazyStringList featureClasses_ = com.google.protobuf.LazyStringArrayList.EMPTY;

            // Construct using spotify.player.proto.PlayOriginOuterClass.PlayOrigin.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return spotify.player.proto.PlayOriginOuterClass.internal_static_spotify_player_proto_PlayOrigin_descriptor;
            }

            @java.lang.Override
            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return spotify.player.proto.PlayOriginOuterClass.internal_static_spotify_player_proto_PlayOrigin_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                spotify.player.proto.PlayOriginOuterClass.PlayOrigin.class, spotify.player.proto.PlayOriginOuterClass.PlayOrigin.Builder.class);
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                }
            }

            @java.lang.Override
            public Builder clear() {
                super.clear();
                featureIdentifier_ = "";
                bitField0_ = (bitField0_ & ~0x00000001);
                featureVersion_ = "";
                bitField0_ = (bitField0_ & ~0x00000002);
                viewUri_ = "";
                bitField0_ = (bitField0_ & ~0x00000004);
                externalReferrer_ = "";
                bitField0_ = (bitField0_ & ~0x00000008);
                referrerIdentifier_ = "";
                bitField0_ = (bitField0_ & ~0x00000010);
                deviceIdentifier_ = "";
                bitField0_ = (bitField0_ & ~0x00000020);
                featureClasses_ = com.google.protobuf.LazyStringArrayList.EMPTY;
                bitField0_ = (bitField0_ & ~0x00000040);
                return this;
            }

            @java.lang.Override
            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return spotify.player.proto.PlayOriginOuterClass.internal_static_spotify_player_proto_PlayOrigin_descriptor;
            }

            @java.lang.Override
            public spotify.player.proto.PlayOriginOuterClass.PlayOrigin getDefaultInstanceForType() {
                return spotify.player.proto.PlayOriginOuterClass.PlayOrigin.getDefaultInstance();
            }

            @java.lang.Override
            public spotify.player.proto.PlayOriginOuterClass.PlayOrigin build() {
                spotify.player.proto.PlayOriginOuterClass.PlayOrigin result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @java.lang.Override
            public spotify.player.proto.PlayOriginOuterClass.PlayOrigin buildPartial() {
                spotify.player.proto.PlayOriginOuterClass.PlayOrigin result = new spotify.player.proto.PlayOriginOuterClass.PlayOrigin(this);
                int from_bitField0_ = bitField0_;
                int to_bitField0_ = 0;
                if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
                    to_bitField0_ |= 0x00000001;
                }
                result.featureIdentifier_ = featureIdentifier_;
                if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
                    to_bitField0_ |= 0x00000002;
                }
                result.featureVersion_ = featureVersion_;
                if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
                    to_bitField0_ |= 0x00000004;
                }
                result.viewUri_ = viewUri_;
                if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
                    to_bitField0_ |= 0x00000008;
                }
                result.externalReferrer_ = externalReferrer_;
                if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
                    to_bitField0_ |= 0x00000010;
                }
                result.referrerIdentifier_ = referrerIdentifier_;
                if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
                    to_bitField0_ |= 0x00000020;
                }
                result.deviceIdentifier_ = deviceIdentifier_;
                if (((bitField0_ & 0x00000040) == 0x00000040)) {
                    featureClasses_ = featureClasses_.getUnmodifiableView();
                    bitField0_ = (bitField0_ & ~0x00000040);
                }
                result.featureClasses_ = featureClasses_;
                result.bitField0_ = to_bitField0_;
                onBuilt();
                return result;
            }

            @java.lang.Override
            public Builder clone() {
                return super.clone();
            }

            @java.lang.Override
            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return super.setField(field, value);
            }

            @java.lang.Override
            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return super.clearField(field);
            }

            @java.lang.Override
            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return super.clearOneof(oneof);
            }

            @java.lang.Override
            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, java.lang.Object value) {
                return super.setRepeatedField(field, index, value);
            }

            @java.lang.Override
            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return super.addRepeatedField(field, value);
            }

            /**
             * <code>optional string feature_identifier = 1;</code>
             */
            public boolean hasFeatureIdentifier() {
                return ((bitField0_ & 0x00000001) == 0x00000001);
            }

            /**
             * <code>optional string feature_identifier = 1;</code>
             */
            public java.lang.String getFeatureIdentifier() {
                java.lang.Object ref = featureIdentifier_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    if (bs.isValidUtf8()) {
                        featureIdentifier_ = s;
                    }
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <code>optional string feature_identifier = 1;</code>
             */
            public Builder setFeatureIdentifier(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000001;
                featureIdentifier_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional string feature_identifier = 1;</code>
             */
            public com.google.protobuf.ByteString
            getFeatureIdentifierBytes() {
                java.lang.Object ref = featureIdentifier_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    featureIdentifier_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>optional string feature_identifier = 1;</code>
             */
            public Builder setFeatureIdentifierBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000001;
                featureIdentifier_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional string feature_identifier = 1;</code>
             */
            public Builder clearFeatureIdentifier() {
                bitField0_ = (bitField0_ & ~0x00000001);
                featureIdentifier_ = getDefaultInstance().getFeatureIdentifier();
                onChanged();
                return this;
            }

            /**
             * <code>optional string feature_version = 2;</code>
             */
            public boolean hasFeatureVersion() {
                return ((bitField0_ & 0x00000002) == 0x00000002);
            }

            /**
             * <code>optional string feature_version = 2;</code>
             */
            public java.lang.String getFeatureVersion() {
                java.lang.Object ref = featureVersion_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    if (bs.isValidUtf8()) {
                        featureVersion_ = s;
                    }
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <code>optional string feature_version = 2;</code>
             */
            public Builder setFeatureVersion(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000002;
                featureVersion_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional string feature_version = 2;</code>
             */
            public com.google.protobuf.ByteString
            getFeatureVersionBytes() {
                java.lang.Object ref = featureVersion_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    featureVersion_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>optional string feature_version = 2;</code>
             */
            public Builder setFeatureVersionBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000002;
                featureVersion_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional string feature_version = 2;</code>
             */
            public Builder clearFeatureVersion() {
                bitField0_ = (bitField0_ & ~0x00000002);
                featureVersion_ = getDefaultInstance().getFeatureVersion();
                onChanged();
                return this;
            }

            /**
             * <code>optional string view_uri = 3;</code>
             */
            public boolean hasViewUri() {
                return ((bitField0_ & 0x00000004) == 0x00000004);
            }

            /**
             * <code>optional string view_uri = 3;</code>
             */
            public java.lang.String getViewUri() {
                java.lang.Object ref = viewUri_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    if (bs.isValidUtf8()) {
                        viewUri_ = s;
                    }
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <code>optional string view_uri = 3;</code>
             */
            public Builder setViewUri(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000004;
                viewUri_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional string view_uri = 3;</code>
             */
            public com.google.protobuf.ByteString
            getViewUriBytes() {
                java.lang.Object ref = viewUri_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    viewUri_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>optional string view_uri = 3;</code>
             */
            public Builder setViewUriBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000004;
                viewUri_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional string view_uri = 3;</code>
             */
            public Builder clearViewUri() {
                bitField0_ = (bitField0_ & ~0x00000004);
                viewUri_ = getDefaultInstance().getViewUri();
                onChanged();
                return this;
            }

            /**
             * <code>optional string external_referrer = 4;</code>
             */
            public boolean hasExternalReferrer() {
                return ((bitField0_ & 0x00000008) == 0x00000008);
            }

            /**
             * <code>optional string external_referrer = 4;</code>
             */
            public java.lang.String getExternalReferrer() {
                java.lang.Object ref = externalReferrer_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    if (bs.isValidUtf8()) {
                        externalReferrer_ = s;
                    }
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <code>optional string external_referrer = 4;</code>
             */
            public Builder setExternalReferrer(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000008;
                externalReferrer_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional string external_referrer = 4;</code>
             */
            public com.google.protobuf.ByteString
            getExternalReferrerBytes() {
                java.lang.Object ref = externalReferrer_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    externalReferrer_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>optional string external_referrer = 4;</code>
             */
            public Builder setExternalReferrerBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000008;
                externalReferrer_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional string external_referrer = 4;</code>
             */
            public Builder clearExternalReferrer() {
                bitField0_ = (bitField0_ & ~0x00000008);
                externalReferrer_ = getDefaultInstance().getExternalReferrer();
                onChanged();
                return this;
            }

            /**
             * <code>optional string referrer_identifier = 5;</code>
             */
            public boolean hasReferrerIdentifier() {
                return ((bitField0_ & 0x00000010) == 0x00000010);
            }

            /**
             * <code>optional string referrer_identifier = 5;</code>
             */
            public java.lang.String getReferrerIdentifier() {
                java.lang.Object ref = referrerIdentifier_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    if (bs.isValidUtf8()) {
                        referrerIdentifier_ = s;
                    }
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <code>optional string referrer_identifier = 5;</code>
             */
            public Builder setReferrerIdentifier(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000010;
                referrerIdentifier_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional string referrer_identifier = 5;</code>
             */
            public com.google.protobuf.ByteString
            getReferrerIdentifierBytes() {
                java.lang.Object ref = referrerIdentifier_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    referrerIdentifier_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>optional string referrer_identifier = 5;</code>
             */
            public Builder setReferrerIdentifierBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000010;
                referrerIdentifier_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional string referrer_identifier = 5;</code>
             */
            public Builder clearReferrerIdentifier() {
                bitField0_ = (bitField0_ & ~0x00000010);
                referrerIdentifier_ = getDefaultInstance().getReferrerIdentifier();
                onChanged();
                return this;
            }

            /**
             * <code>optional string device_identifier = 6;</code>
             */
            public boolean hasDeviceIdentifier() {
                return ((bitField0_ & 0x00000020) == 0x00000020);
            }

            /**
             * <code>optional string device_identifier = 6;</code>
             */
            public java.lang.String getDeviceIdentifier() {
                java.lang.Object ref = deviceIdentifier_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    if (bs.isValidUtf8()) {
                        deviceIdentifier_ = s;
                    }
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <code>optional string device_identifier = 6;</code>
             */
            public Builder setDeviceIdentifier(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000020;
                deviceIdentifier_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional string device_identifier = 6;</code>
             */
            public com.google.protobuf.ByteString
            getDeviceIdentifierBytes() {
                java.lang.Object ref = deviceIdentifier_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    deviceIdentifier_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>optional string device_identifier = 6;</code>
             */
            public Builder setDeviceIdentifierBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000020;
                deviceIdentifier_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional string device_identifier = 6;</code>
             */
            public Builder clearDeviceIdentifier() {
                bitField0_ = (bitField0_ & ~0x00000020);
                deviceIdentifier_ = getDefaultInstance().getDeviceIdentifier();
                onChanged();
                return this;
            }

            private void ensureFeatureClassesIsMutable() {
                if (!((bitField0_ & 0x00000040) == 0x00000040)) {
                    featureClasses_ = new com.google.protobuf.LazyStringArrayList(featureClasses_);
                    bitField0_ |= 0x00000040;
                }
            }

            /**
             * <code>repeated string feature_classes = 7;</code>
             */
            public com.google.protobuf.ProtocolStringList
            getFeatureClassesList() {
                return featureClasses_.getUnmodifiableView();
            }

            /**
             * <code>repeated string feature_classes = 7;</code>
             */
            public int getFeatureClassesCount() {
                return featureClasses_.size();
            }

            /**
             * <code>repeated string feature_classes = 7;</code>
             */
            public java.lang.String getFeatureClasses(int index) {
                return featureClasses_.get(index);
            }

            /**
             * <code>repeated string feature_classes = 7;</code>
             */
            public com.google.protobuf.ByteString
            getFeatureClassesBytes(int index) {
                return featureClasses_.getByteString(index);
            }

            /**
             * <code>repeated string feature_classes = 7;</code>
             */
            public Builder setFeatureClasses(
                    int index, java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                ensureFeatureClassesIsMutable();
                featureClasses_.set(index, value);
                onChanged();
                return this;
            }

            /**
             * <code>repeated string feature_classes = 7;</code>
             */
            public Builder addFeatureClasses(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                ensureFeatureClassesIsMutable();
                featureClasses_.add(value);
                onChanged();
                return this;
            }

            /**
             * <code>repeated string feature_classes = 7;</code>
             */
            public Builder addAllFeatureClasses(
                    java.lang.Iterable<java.lang.String> values) {
                ensureFeatureClassesIsMutable();
                com.google.protobuf.AbstractMessageLite.Builder.addAll(
                        values, featureClasses_);
                onChanged();
                return this;
            }

            /**
             * <code>repeated string feature_classes = 7;</code>
             */
            public Builder clearFeatureClasses() {
                featureClasses_ = com.google.protobuf.LazyStringArrayList.EMPTY;
                bitField0_ = (bitField0_ & ~0x00000040);
                onChanged();
                return this;
            }

            /**
             * <code>repeated string feature_classes = 7;</code>
             */
            public Builder addFeatureClassesBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                ensureFeatureClassesIsMutable();
                featureClasses_.add(value);
                onChanged();
                return this;
            }

            @java.lang.Override
            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.setUnknownFields(unknownFields);
            }

            @java.lang.Override
            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.mergeUnknownFields(unknownFields);
            }


            // @@protoc_insertion_point(builder_scope:spotify.player.proto.PlayOrigin)
        }

    }

    // @@protoc_insertion_point(outer_class_scope)
}
