// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: storage-resolve.proto

package xyz.gianlu.librespot.cdn;

@SuppressWarnings("unused")
public final class StorageResolve {
    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_InteractiveAudioFiles_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_InteractiveAudioFiles_fieldAccessorTable;
    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static {
        java.lang.String[] descriptorData = {
                "\n\025storage-resolve.proto\"6\n\025InteractiveAu" +
                        "dioFiles\022\014\n\004uris\030\002 \003(\t\022\017\n\007file_id\030\004 \001(\014"
        };
        com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
                new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
                    public com.google.protobuf.ExtensionRegistry assignDescriptors(
                            com.google.protobuf.Descriptors.FileDescriptor root) {
                        descriptor = root;
                        return null;
                    }
                };
        com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{
                        }, assigner);
        internal_static_InteractiveAudioFiles_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_InteractiveAudioFiles_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_InteractiveAudioFiles_descriptor,
                new java.lang.String[]{"Uris", "FileId",});
    }

    private StorageResolve() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }

    public interface InteractiveAudioFilesOrBuilder extends
            // @@protoc_insertion_point(interface_extends:InteractiveAudioFiles)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <pre>
         * optional uint32 unknown = 1;
         * </pre>
         *
         * <code>repeated string uris = 2;</code>
         */
        java.util.List<java.lang.String>
        getUrisList();

        /**
         * <pre>
         * optional uint32 unknown = 1;
         * </pre>
         *
         * <code>repeated string uris = 2;</code>
         */
        int getUrisCount();

        /**
         * <pre>
         * optional uint32 unknown = 1;
         * </pre>
         *
         * <code>repeated string uris = 2;</code>
         */
        java.lang.String getUris(int index);

        /**
         * <pre>
         * optional uint32 unknown = 1;
         * </pre>
         *
         * <code>repeated string uris = 2;</code>
         */
        com.google.protobuf.ByteString
        getUrisBytes(int index);

        /**
         * <code>optional bytes file_id = 4;</code>
         */
        boolean hasFileId();

        /**
         * <code>optional bytes file_id = 4;</code>
         */
        com.google.protobuf.ByteString getFileId();
    }

    /**
     * Protobuf type {@code InteractiveAudioFiles}
     */
    public static final class InteractiveAudioFiles extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:InteractiveAudioFiles)
            InteractiveAudioFilesOrBuilder {
        public static final int URIS_FIELD_NUMBER = 2;
        public static final int FILE_ID_FIELD_NUMBER = 4;
        @java.lang.Deprecated
        public static final com.google.protobuf.Parser<InteractiveAudioFiles>
                PARSER = new com.google.protobuf.AbstractParser<InteractiveAudioFiles>() {
            @java.lang.Override
            public InteractiveAudioFiles parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new InteractiveAudioFiles(input, extensionRegistry);
            }
        };
        private static final long serialVersionUID = 0L;
        // @@protoc_insertion_point(class_scope:InteractiveAudioFiles)
        private static final StorageResolve.InteractiveAudioFiles DEFAULT_INSTANCE;

        static {
            DEFAULT_INSTANCE = new StorageResolve.InteractiveAudioFiles();
        }

        private int bitField0_;
        private com.google.protobuf.LazyStringList uris_;
        private com.google.protobuf.ByteString fileId_;
        private byte memoizedIsInitialized = -1;

        // Use InteractiveAudioFiles.newBuilder() to construct.
        private InteractiveAudioFiles(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }

        private InteractiveAudioFiles() {
            uris_ = com.google.protobuf.LazyStringArrayList.EMPTY;
            fileId_ = com.google.protobuf.ByteString.EMPTY;
        }

        private InteractiveAudioFiles(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            if (extensionRegistry == null) {
                throw new java.lang.NullPointerException();
            }
            int mutable_bitField0_ = 0;
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                    com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        case 18: {
                            com.google.protobuf.ByteString bs = input.readBytes();
                            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                                uris_ = new com.google.protobuf.LazyStringArrayList();
                                mutable_bitField0_ |= 0x00000001;
                            }
                            uris_.add(bs);
                            break;
                        }
                        case 34: {
                            bitField0_ |= 0x00000001;
                            fileId_ = input.readBytes();
                            break;
                        }
                        default: {
                            if (!parseUnknownField(
                                    input, unknownFields, extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                    uris_ = uris_.getUnmodifiableView();
                }
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return StorageResolve.internal_static_InteractiveAudioFiles_descriptor;
        }

        public static StorageResolve.InteractiveAudioFiles parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static StorageResolve.InteractiveAudioFiles parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static StorageResolve.InteractiveAudioFiles parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static StorageResolve.InteractiveAudioFiles parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static StorageResolve.InteractiveAudioFiles parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static StorageResolve.InteractiveAudioFiles parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static StorageResolve.InteractiveAudioFiles parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static StorageResolve.InteractiveAudioFiles parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static StorageResolve.InteractiveAudioFiles parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }

        public static StorageResolve.InteractiveAudioFiles parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static StorageResolve.InteractiveAudioFiles parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static StorageResolve.InteractiveAudioFiles parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(StorageResolve.InteractiveAudioFiles prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        public static StorageResolve.InteractiveAudioFiles getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        public static com.google.protobuf.Parser<InteractiveAudioFiles> parser() {
            return PARSER;
        }

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return this.unknownFields;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return StorageResolve.internal_static_InteractiveAudioFiles_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            StorageResolve.InteractiveAudioFiles.class, StorageResolve.InteractiveAudioFiles.Builder.class);
        }

        /**
         * <pre>
         * optional uint32 unknown = 1;
         * </pre>
         *
         * <code>repeated string uris = 2;</code>
         */
        public com.google.protobuf.ProtocolStringList
        getUrisList() {
            return uris_;
        }

        /**
         * <pre>
         * optional uint32 unknown = 1;
         * </pre>
         *
         * <code>repeated string uris = 2;</code>
         */
        public int getUrisCount() {
            return uris_.size();
        }

        /**
         * <pre>
         * optional uint32 unknown = 1;
         * </pre>
         *
         * <code>repeated string uris = 2;</code>
         */
        public java.lang.String getUris(int index) {
            return uris_.get(index);
        }

        /**
         * <pre>
         * optional uint32 unknown = 1;
         * </pre>
         *
         * <code>repeated string uris = 2;</code>
         */
        public com.google.protobuf.ByteString
        getUrisBytes(int index) {
            return uris_.getByteString(index);
        }

        /**
         * <code>optional bytes file_id = 4;</code>
         */
        public boolean hasFileId() {
            return ((bitField0_ & 0x00000001) == 0x00000001);
        }

        /**
         * <code>optional bytes file_id = 4;</code>
         */
        public com.google.protobuf.ByteString getFileId() {
            return fileId_;
        }

        @java.lang.Override
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        @java.lang.Override
        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            for (int i = 0; i < uris_.size(); i++) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 2, uris_.getRaw(i));
            }
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                output.writeBytes(4, fileId_);
            }
            unknownFields.writeTo(output);
        }

        @java.lang.Override
        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            {
                int dataSize = 0;
                for (int i = 0; i < uris_.size(); i++) {
                    dataSize += computeStringSizeNoTag(uris_.getRaw(i));
                }
                size += dataSize;
                size += 1 * getUrisList().size();
            }
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBytesSize(4, fileId_);
            }
            size += unknownFields.getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof StorageResolve.InteractiveAudioFiles)) {
                return super.equals(obj);
            }
            StorageResolve.InteractiveAudioFiles other = (StorageResolve.InteractiveAudioFiles) obj;

            boolean result = true;
            result = result && getUrisList()
                    .equals(other.getUrisList());
            result = result && (hasFileId() == other.hasFileId());
            if (hasFileId()) {
                result = result && getFileId()
                        .equals(other.getFileId());
            }
            result = result && unknownFields.equals(other.unknownFields);
            return result;
        }

        @java.lang.Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            if (getUrisCount() > 0) {
                hash = (37 * hash) + URIS_FIELD_NUMBER;
                hash = (53 * hash) + getUrisList().hashCode();
            }
            if (hasFileId()) {
                hash = (37 * hash) + FILE_ID_FIELD_NUMBER;
                hash = (53 * hash) + getFileId().hashCode();
            }
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        @java.lang.Override
        public Builder newBuilderForType() {
            return newBuilder();
        }

        @java.lang.Override
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<InteractiveAudioFiles> getParserForType() {
            return PARSER;
        }

        @java.lang.Override
        public StorageResolve.InteractiveAudioFiles getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

        /**
         * Protobuf type {@code InteractiveAudioFiles}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:InteractiveAudioFiles)
                StorageResolve.InteractiveAudioFilesOrBuilder {
            private int bitField0_;
            private com.google.protobuf.LazyStringList uris_ = com.google.protobuf.LazyStringArrayList.EMPTY;
            private com.google.protobuf.ByteString fileId_ = com.google.protobuf.ByteString.EMPTY;

            // Construct using StorageResolve.InteractiveAudioFiles.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return StorageResolve.internal_static_InteractiveAudioFiles_descriptor;
            }

            @java.lang.Override
            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return StorageResolve.internal_static_InteractiveAudioFiles_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                StorageResolve.InteractiveAudioFiles.class, StorageResolve.InteractiveAudioFiles.Builder.class);
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                }
            }

            @java.lang.Override
            public Builder clear() {
                super.clear();
                uris_ = com.google.protobuf.LazyStringArrayList.EMPTY;
                bitField0_ = (bitField0_ & ~0x00000001);
                fileId_ = com.google.protobuf.ByteString.EMPTY;
                bitField0_ = (bitField0_ & ~0x00000002);
                return this;
            }

            @java.lang.Override
            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return StorageResolve.internal_static_InteractiveAudioFiles_descriptor;
            }

            @java.lang.Override
            public StorageResolve.InteractiveAudioFiles getDefaultInstanceForType() {
                return StorageResolve.InteractiveAudioFiles.getDefaultInstance();
            }

            @java.lang.Override
            public StorageResolve.InteractiveAudioFiles build() {
                StorageResolve.InteractiveAudioFiles result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @java.lang.Override
            public StorageResolve.InteractiveAudioFiles buildPartial() {
                StorageResolve.InteractiveAudioFiles result = new StorageResolve.InteractiveAudioFiles(this);
                int from_bitField0_ = bitField0_;
                int to_bitField0_ = 0;
                if (((bitField0_ & 0x00000001) == 0x00000001)) {
                    uris_ = uris_.getUnmodifiableView();
                    bitField0_ = (bitField0_ & ~0x00000001);
                }
                result.uris_ = uris_;
                if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
                    to_bitField0_ |= 0x00000001;
                }
                result.fileId_ = fileId_;
                result.bitField0_ = to_bitField0_;
                onBuilt();
                return result;
            }

            @java.lang.Override
            public Builder clone() {
                return super.clone();
            }

            @java.lang.Override
            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return super.setField(field, value);
            }

            @java.lang.Override
            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return super.clearField(field);
            }

            @java.lang.Override
            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return super.clearOneof(oneof);
            }

            @java.lang.Override
            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, java.lang.Object value) {
                return super.setRepeatedField(field, index, value);
            }

            @java.lang.Override
            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return super.addRepeatedField(field, value);
            }

            @java.lang.Override
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof StorageResolve.InteractiveAudioFiles) {
                    return mergeFrom((StorageResolve.InteractiveAudioFiles) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(StorageResolve.InteractiveAudioFiles other) {
                if (other == StorageResolve.InteractiveAudioFiles.getDefaultInstance()) return this;
                if (!other.uris_.isEmpty()) {
                    if (uris_.isEmpty()) {
                        uris_ = other.uris_;
                        bitField0_ = (bitField0_ & ~0x00000001);
                    } else {
                        ensureUrisIsMutable();
                        uris_.addAll(other.uris_);
                    }
                    onChanged();
                }
                if (other.hasFileId()) {
                    setFileId(other.getFileId());
                }
                this.mergeUnknownFields(other.unknownFields);
                onChanged();
                return this;
            }

            @java.lang.Override
            public final boolean isInitialized() {
                return true;
            }

            @java.lang.Override
            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                StorageResolve.InteractiveAudioFiles parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (StorageResolve.InteractiveAudioFiles) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private void ensureUrisIsMutable() {
                if (!((bitField0_ & 0x00000001) == 0x00000001)) {
                    uris_ = new com.google.protobuf.LazyStringArrayList(uris_);
                    bitField0_ |= 0x00000001;
                }
            }

            /**
             * <pre>
             * optional uint32 unknown = 1;
             * </pre>
             *
             * <code>repeated string uris = 2;</code>
             */
            public com.google.protobuf.ProtocolStringList
            getUrisList() {
                return uris_.getUnmodifiableView();
            }

            /**
             * <pre>
             * optional uint32 unknown = 1;
             * </pre>
             *
             * <code>repeated string uris = 2;</code>
             */
            public int getUrisCount() {
                return uris_.size();
            }

            /**
             * <pre>
             * optional uint32 unknown = 1;
             * </pre>
             *
             * <code>repeated string uris = 2;</code>
             */
            public java.lang.String getUris(int index) {
                return uris_.get(index);
            }

            /**
             * <pre>
             * optional uint32 unknown = 1;
             * </pre>
             *
             * <code>repeated string uris = 2;</code>
             */
            public com.google.protobuf.ByteString
            getUrisBytes(int index) {
                return uris_.getByteString(index);
            }

            /**
             * <pre>
             * optional uint32 unknown = 1;
             * </pre>
             *
             * <code>repeated string uris = 2;</code>
             */
            public Builder setUris(
                    int index, java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                ensureUrisIsMutable();
                uris_.set(index, value);
                onChanged();
                return this;
            }

            /**
             * <pre>
             * optional uint32 unknown = 1;
             * </pre>
             *
             * <code>repeated string uris = 2;</code>
             */
            public Builder addUris(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                ensureUrisIsMutable();
                uris_.add(value);
                onChanged();
                return this;
            }

            /**
             * <pre>
             * optional uint32 unknown = 1;
             * </pre>
             *
             * <code>repeated string uris = 2;</code>
             */
            public Builder addAllUris(
                    java.lang.Iterable<java.lang.String> values) {
                ensureUrisIsMutable();
                com.google.protobuf.AbstractMessageLite.Builder.addAll(
                        values, uris_);
                onChanged();
                return this;
            }

            /**
             * <pre>
             * optional uint32 unknown = 1;
             * </pre>
             *
             * <code>repeated string uris = 2;</code>
             */
            public Builder clearUris() {
                uris_ = com.google.protobuf.LazyStringArrayList.EMPTY;
                bitField0_ = (bitField0_ & ~0x00000001);
                onChanged();
                return this;
            }

            /**
             * <pre>
             * optional uint32 unknown = 1;
             * </pre>
             *
             * <code>repeated string uris = 2;</code>
             */
            public Builder addUrisBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                ensureUrisIsMutable();
                uris_.add(value);
                onChanged();
                return this;
            }

            /**
             * <code>optional bytes file_id = 4;</code>
             */
            public boolean hasFileId() {
                return ((bitField0_ & 0x00000002) == 0x00000002);
            }

            /**
             * <code>optional bytes file_id = 4;</code>
             */
            public com.google.protobuf.ByteString getFileId() {
                return fileId_;
            }

            /**
             * <code>optional bytes file_id = 4;</code>
             */
            public Builder setFileId(com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000002;
                fileId_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional bytes file_id = 4;</code>
             */
            public Builder clearFileId() {
                bitField0_ = (bitField0_ & ~0x00000002);
                fileId_ = getDefaultInstance().getFileId();
                onChanged();
                return this;
            }

            @java.lang.Override
            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.setUnknownFields(unknownFields);
            }

            @java.lang.Override
            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.mergeUnknownFields(unknownFields);
            }


            // @@protoc_insertion_point(builder_scope:InteractiveAudioFiles)
        }

    }

    // @@protoc_insertion_point(outer_class_scope)
}
