// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: social.proto

package xyz.gianlu.librespot.common.proto;

@SuppressWarnings("ALL")
public final class Social {
    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_DecorationData_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_DecorationData_fieldAccessorTable;
    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static {
        java.lang.String[] descriptorData = {
                "\n\014social.proto\"\236\001\n\016DecorationData\022\020\n\010use" +
                        "rname\030\001 \001(\t\022\021\n\tfull_name\030\002 \001(\t\022\021\n\timage_" +
                        "url\030\003 \001(\t\022\027\n\017large_image_url\030\005 \001(\t\022\022\n\nfi" +
                        "rst_name\030\006 \001(\t\022\021\n\tlast_name\030\007 \001(\t\022\024\n\014fac" +
                        "ebook_uid\030\010 \001(\t"
        };
        com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
                new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
                    public com.google.protobuf.ExtensionRegistry assignDescriptors(
                            com.google.protobuf.Descriptors.FileDescriptor root) {
                        descriptor = root;
                        return null;
                    }
                };
        com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{
                        }, assigner);
        internal_static_DecorationData_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_DecorationData_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_DecorationData_descriptor,
                new java.lang.String[]{"Username", "FullName", "ImageUrl", "LargeImageUrl", "FirstName", "LastName", "FacebookUid",});
    }

    private Social() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }

    public interface DecorationDataOrBuilder extends
            // @@protoc_insertion_point(interface_extends:DecorationData)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>optional string username = 1;</code>
         */
        boolean hasUsername();

        /**
         * <code>optional string username = 1;</code>
         */
        java.lang.String getUsername();

        /**
         * <code>optional string username = 1;</code>
         */
        com.google.protobuf.ByteString
        getUsernameBytes();

        /**
         * <code>optional string full_name = 2;</code>
         */
        boolean hasFullName();

        /**
         * <code>optional string full_name = 2;</code>
         */
        java.lang.String getFullName();

        /**
         * <code>optional string full_name = 2;</code>
         */
        com.google.protobuf.ByteString
        getFullNameBytes();

        /**
         * <code>optional string image_url = 3;</code>
         */
        boolean hasImageUrl();

        /**
         * <code>optional string image_url = 3;</code>
         */
        java.lang.String getImageUrl();

        /**
         * <code>optional string image_url = 3;</code>
         */
        com.google.protobuf.ByteString
        getImageUrlBytes();

        /**
         * <code>optional string large_image_url = 5;</code>
         */
        boolean hasLargeImageUrl();

        /**
         * <code>optional string large_image_url = 5;</code>
         */
        java.lang.String getLargeImageUrl();

        /**
         * <code>optional string large_image_url = 5;</code>
         */
        com.google.protobuf.ByteString
        getLargeImageUrlBytes();

        /**
         * <code>optional string first_name = 6;</code>
         */
        boolean hasFirstName();

        /**
         * <code>optional string first_name = 6;</code>
         */
        java.lang.String getFirstName();

        /**
         * <code>optional string first_name = 6;</code>
         */
        com.google.protobuf.ByteString
        getFirstNameBytes();

        /**
         * <code>optional string last_name = 7;</code>
         */
        boolean hasLastName();

        /**
         * <code>optional string last_name = 7;</code>
         */
        java.lang.String getLastName();

        /**
         * <code>optional string last_name = 7;</code>
         */
        com.google.protobuf.ByteString
        getLastNameBytes();

        /**
         * <code>optional string facebook_uid = 8;</code>
         */
        boolean hasFacebookUid();

        /**
         * <code>optional string facebook_uid = 8;</code>
         */
        java.lang.String getFacebookUid();

        /**
         * <code>optional string facebook_uid = 8;</code>
         */
        com.google.protobuf.ByteString
        getFacebookUidBytes();
    }

    /**
     * Protobuf type {@code DecorationData}
     */
    public static final class DecorationData extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:DecorationData)
            DecorationDataOrBuilder {
        public static final int USERNAME_FIELD_NUMBER = 1;
        public static final int FULL_NAME_FIELD_NUMBER = 2;
        public static final int IMAGE_URL_FIELD_NUMBER = 3;
        public static final int LARGE_IMAGE_URL_FIELD_NUMBER = 5;
        public static final int FIRST_NAME_FIELD_NUMBER = 6;
        public static final int LAST_NAME_FIELD_NUMBER = 7;
        public static final int FACEBOOK_UID_FIELD_NUMBER = 8;
        @java.lang.Deprecated
        public static final com.google.protobuf.Parser<DecorationData>
                PARSER = new com.google.protobuf.AbstractParser<DecorationData>() {
            @java.lang.Override
            public DecorationData parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new DecorationData(input, extensionRegistry);
            }
        };
        private static final long serialVersionUID = 0L;
        // @@protoc_insertion_point(class_scope:DecorationData)
        private static final Social.DecorationData DEFAULT_INSTANCE;

        static {
            DEFAULT_INSTANCE = new Social.DecorationData();
        }

        private int bitField0_;
        private volatile java.lang.Object username_;
        private volatile java.lang.Object fullName_;
        private volatile java.lang.Object imageUrl_;
        private volatile java.lang.Object largeImageUrl_;
        private volatile java.lang.Object firstName_;
        private volatile java.lang.Object lastName_;
        private volatile java.lang.Object facebookUid_;
        private byte memoizedIsInitialized = -1;

        // Use DecorationData.newBuilder() to construct.
        private DecorationData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }

        private DecorationData() {
            username_ = "";
            fullName_ = "";
            imageUrl_ = "";
            largeImageUrl_ = "";
            firstName_ = "";
            lastName_ = "";
            facebookUid_ = "";
        }

        private DecorationData(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            if (extensionRegistry == null) {
                throw new java.lang.NullPointerException();
            }
            int mutable_bitField0_ = 0;
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                    com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        case 10: {
                            com.google.protobuf.ByteString bs = input.readBytes();
                            bitField0_ |= 0x00000001;
                            username_ = bs;
                            break;
                        }
                        case 18: {
                            com.google.protobuf.ByteString bs = input.readBytes();
                            bitField0_ |= 0x00000002;
                            fullName_ = bs;
                            break;
                        }
                        case 26: {
                            com.google.protobuf.ByteString bs = input.readBytes();
                            bitField0_ |= 0x00000004;
                            imageUrl_ = bs;
                            break;
                        }
                        case 42: {
                            com.google.protobuf.ByteString bs = input.readBytes();
                            bitField0_ |= 0x00000008;
                            largeImageUrl_ = bs;
                            break;
                        }
                        case 50: {
                            com.google.protobuf.ByteString bs = input.readBytes();
                            bitField0_ |= 0x00000010;
                            firstName_ = bs;
                            break;
                        }
                        case 58: {
                            com.google.protobuf.ByteString bs = input.readBytes();
                            bitField0_ |= 0x00000020;
                            lastName_ = bs;
                            break;
                        }
                        case 66: {
                            com.google.protobuf.ByteString bs = input.readBytes();
                            bitField0_ |= 0x00000040;
                            facebookUid_ = bs;
                            break;
                        }
                        default: {
                            if (!parseUnknownField(
                                    input, unknownFields, extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return Social.internal_static_DecorationData_descriptor;
        }

        public static Social.DecorationData parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static Social.DecorationData parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static Social.DecorationData parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static Social.DecorationData parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static Social.DecorationData parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static Social.DecorationData parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static Social.DecorationData parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static Social.DecorationData parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static Social.DecorationData parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }

        public static Social.DecorationData parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static Social.DecorationData parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static Social.DecorationData parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(Social.DecorationData prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        public static Social.DecorationData getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        public static com.google.protobuf.Parser<DecorationData> parser() {
            return PARSER;
        }

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return this.unknownFields;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return Social.internal_static_DecorationData_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            Social.DecorationData.class, Social.DecorationData.Builder.class);
        }

        /**
         * <code>optional string username = 1;</code>
         */
        public boolean hasUsername() {
            return ((bitField0_ & 0x00000001) == 0x00000001);
        }

        /**
         * <code>optional string username = 1;</code>
         */
        public java.lang.String getUsername() {
            java.lang.Object ref = username_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                if (bs.isValidUtf8()) {
                    username_ = s;
                }
                return s;
            }
        }

        /**
         * <code>optional string username = 1;</code>
         */
        public com.google.protobuf.ByteString
        getUsernameBytes() {
            java.lang.Object ref = username_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                username_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>optional string full_name = 2;</code>
         */
        public boolean hasFullName() {
            return ((bitField0_ & 0x00000002) == 0x00000002);
        }

        /**
         * <code>optional string full_name = 2;</code>
         */
        public java.lang.String getFullName() {
            java.lang.Object ref = fullName_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                if (bs.isValidUtf8()) {
                    fullName_ = s;
                }
                return s;
            }
        }

        /**
         * <code>optional string full_name = 2;</code>
         */
        public com.google.protobuf.ByteString
        getFullNameBytes() {
            java.lang.Object ref = fullName_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                fullName_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>optional string image_url = 3;</code>
         */
        public boolean hasImageUrl() {
            return ((bitField0_ & 0x00000004) == 0x00000004);
        }

        /**
         * <code>optional string image_url = 3;</code>
         */
        public java.lang.String getImageUrl() {
            java.lang.Object ref = imageUrl_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                if (bs.isValidUtf8()) {
                    imageUrl_ = s;
                }
                return s;
            }
        }

        /**
         * <code>optional string image_url = 3;</code>
         */
        public com.google.protobuf.ByteString
        getImageUrlBytes() {
            java.lang.Object ref = imageUrl_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                imageUrl_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>optional string large_image_url = 5;</code>
         */
        public boolean hasLargeImageUrl() {
            return ((bitField0_ & 0x00000008) == 0x00000008);
        }

        /**
         * <code>optional string large_image_url = 5;</code>
         */
        public java.lang.String getLargeImageUrl() {
            java.lang.Object ref = largeImageUrl_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                if (bs.isValidUtf8()) {
                    largeImageUrl_ = s;
                }
                return s;
            }
        }

        /**
         * <code>optional string large_image_url = 5;</code>
         */
        public com.google.protobuf.ByteString
        getLargeImageUrlBytes() {
            java.lang.Object ref = largeImageUrl_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                largeImageUrl_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>optional string first_name = 6;</code>
         */
        public boolean hasFirstName() {
            return ((bitField0_ & 0x00000010) == 0x00000010);
        }

        /**
         * <code>optional string first_name = 6;</code>
         */
        public java.lang.String getFirstName() {
            java.lang.Object ref = firstName_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                if (bs.isValidUtf8()) {
                    firstName_ = s;
                }
                return s;
            }
        }

        /**
         * <code>optional string first_name = 6;</code>
         */
        public com.google.protobuf.ByteString
        getFirstNameBytes() {
            java.lang.Object ref = firstName_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                firstName_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>optional string last_name = 7;</code>
         */
        public boolean hasLastName() {
            return ((bitField0_ & 0x00000020) == 0x00000020);
        }

        /**
         * <code>optional string last_name = 7;</code>
         */
        public java.lang.String getLastName() {
            java.lang.Object ref = lastName_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                if (bs.isValidUtf8()) {
                    lastName_ = s;
                }
                return s;
            }
        }

        /**
         * <code>optional string last_name = 7;</code>
         */
        public com.google.protobuf.ByteString
        getLastNameBytes() {
            java.lang.Object ref = lastName_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                lastName_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>optional string facebook_uid = 8;</code>
         */
        public boolean hasFacebookUid() {
            return ((bitField0_ & 0x00000040) == 0x00000040);
        }

        /**
         * <code>optional string facebook_uid = 8;</code>
         */
        public java.lang.String getFacebookUid() {
            java.lang.Object ref = facebookUid_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                if (bs.isValidUtf8()) {
                    facebookUid_ = s;
                }
                return s;
            }
        }

        /**
         * <code>optional string facebook_uid = 8;</code>
         */
        public com.google.protobuf.ByteString
        getFacebookUidBytes() {
            java.lang.Object ref = facebookUid_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                facebookUid_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        @java.lang.Override
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        @java.lang.Override
        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 1, username_);
            }
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 2, fullName_);
            }
            if (((bitField0_ & 0x00000004) == 0x00000004)) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 3, imageUrl_);
            }
            if (((bitField0_ & 0x00000008) == 0x00000008)) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 5, largeImageUrl_);
            }
            if (((bitField0_ & 0x00000010) == 0x00000010)) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 6, firstName_);
            }
            if (((bitField0_ & 0x00000020) == 0x00000020)) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 7, lastName_);
            }
            if (((bitField0_ & 0x00000040) == 0x00000040)) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 8, facebookUid_);
            }
            unknownFields.writeTo(output);
        }

        @java.lang.Override
        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, username_);
            }
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, fullName_);
            }
            if (((bitField0_ & 0x00000004) == 0x00000004)) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, imageUrl_);
            }
            if (((bitField0_ & 0x00000008) == 0x00000008)) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, largeImageUrl_);
            }
            if (((bitField0_ & 0x00000010) == 0x00000010)) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, firstName_);
            }
            if (((bitField0_ & 0x00000020) == 0x00000020)) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, lastName_);
            }
            if (((bitField0_ & 0x00000040) == 0x00000040)) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, facebookUid_);
            }
            size += unknownFields.getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof Social.DecorationData)) {
                return super.equals(obj);
            }
            Social.DecorationData other = (Social.DecorationData) obj;

            boolean result = true;
            result = result && (hasUsername() == other.hasUsername());
            if (hasUsername()) {
                result = result && getUsername()
                        .equals(other.getUsername());
            }
            result = result && (hasFullName() == other.hasFullName());
            if (hasFullName()) {
                result = result && getFullName()
                        .equals(other.getFullName());
            }
            result = result && (hasImageUrl() == other.hasImageUrl());
            if (hasImageUrl()) {
                result = result && getImageUrl()
                        .equals(other.getImageUrl());
            }
            result = result && (hasLargeImageUrl() == other.hasLargeImageUrl());
            if (hasLargeImageUrl()) {
                result = result && getLargeImageUrl()
                        .equals(other.getLargeImageUrl());
            }
            result = result && (hasFirstName() == other.hasFirstName());
            if (hasFirstName()) {
                result = result && getFirstName()
                        .equals(other.getFirstName());
            }
            result = result && (hasLastName() == other.hasLastName());
            if (hasLastName()) {
                result = result && getLastName()
                        .equals(other.getLastName());
            }
            result = result && (hasFacebookUid() == other.hasFacebookUid());
            if (hasFacebookUid()) {
                result = result && getFacebookUid()
                        .equals(other.getFacebookUid());
            }
            result = result && unknownFields.equals(other.unknownFields);
            return result;
        }

        @java.lang.Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            if (hasUsername()) {
                hash = (37 * hash) + USERNAME_FIELD_NUMBER;
                hash = (53 * hash) + getUsername().hashCode();
            }
            if (hasFullName()) {
                hash = (37 * hash) + FULL_NAME_FIELD_NUMBER;
                hash = (53 * hash) + getFullName().hashCode();
            }
            if (hasImageUrl()) {
                hash = (37 * hash) + IMAGE_URL_FIELD_NUMBER;
                hash = (53 * hash) + getImageUrl().hashCode();
            }
            if (hasLargeImageUrl()) {
                hash = (37 * hash) + LARGE_IMAGE_URL_FIELD_NUMBER;
                hash = (53 * hash) + getLargeImageUrl().hashCode();
            }
            if (hasFirstName()) {
                hash = (37 * hash) + FIRST_NAME_FIELD_NUMBER;
                hash = (53 * hash) + getFirstName().hashCode();
            }
            if (hasLastName()) {
                hash = (37 * hash) + LAST_NAME_FIELD_NUMBER;
                hash = (53 * hash) + getLastName().hashCode();
            }
            if (hasFacebookUid()) {
                hash = (37 * hash) + FACEBOOK_UID_FIELD_NUMBER;
                hash = (53 * hash) + getFacebookUid().hashCode();
            }
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        @java.lang.Override
        public Builder newBuilderForType() {
            return newBuilder();
        }

        @java.lang.Override
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<DecorationData> getParserForType() {
            return PARSER;
        }

        @java.lang.Override
        public Social.DecorationData getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

        /**
         * Protobuf type {@code DecorationData}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:DecorationData)
                Social.DecorationDataOrBuilder {
            private int bitField0_;
            private java.lang.Object username_ = "";
            private java.lang.Object fullName_ = "";
            private java.lang.Object imageUrl_ = "";
            private java.lang.Object largeImageUrl_ = "";
            private java.lang.Object firstName_ = "";
            private java.lang.Object lastName_ = "";
            private java.lang.Object facebookUid_ = "";

            // Construct using Social.DecorationData.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return Social.internal_static_DecorationData_descriptor;
            }

            @java.lang.Override
            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return Social.internal_static_DecorationData_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                Social.DecorationData.class, Social.DecorationData.Builder.class);
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                }
            }

            @java.lang.Override
            public Builder clear() {
                super.clear();
                username_ = "";
                bitField0_ = (bitField0_ & ~0x00000001);
                fullName_ = "";
                bitField0_ = (bitField0_ & ~0x00000002);
                imageUrl_ = "";
                bitField0_ = (bitField0_ & ~0x00000004);
                largeImageUrl_ = "";
                bitField0_ = (bitField0_ & ~0x00000008);
                firstName_ = "";
                bitField0_ = (bitField0_ & ~0x00000010);
                lastName_ = "";
                bitField0_ = (bitField0_ & ~0x00000020);
                facebookUid_ = "";
                bitField0_ = (bitField0_ & ~0x00000040);
                return this;
            }

            @java.lang.Override
            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return Social.internal_static_DecorationData_descriptor;
            }

            @java.lang.Override
            public Social.DecorationData getDefaultInstanceForType() {
                return Social.DecorationData.getDefaultInstance();
            }

            @java.lang.Override
            public Social.DecorationData build() {
                Social.DecorationData result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @java.lang.Override
            public Social.DecorationData buildPartial() {
                Social.DecorationData result = new Social.DecorationData(this);
                int from_bitField0_ = bitField0_;
                int to_bitField0_ = 0;
                if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
                    to_bitField0_ |= 0x00000001;
                }
                result.username_ = username_;
                if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
                    to_bitField0_ |= 0x00000002;
                }
                result.fullName_ = fullName_;
                if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
                    to_bitField0_ |= 0x00000004;
                }
                result.imageUrl_ = imageUrl_;
                if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
                    to_bitField0_ |= 0x00000008;
                }
                result.largeImageUrl_ = largeImageUrl_;
                if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
                    to_bitField0_ |= 0x00000010;
                }
                result.firstName_ = firstName_;
                if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
                    to_bitField0_ |= 0x00000020;
                }
                result.lastName_ = lastName_;
                if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
                    to_bitField0_ |= 0x00000040;
                }
                result.facebookUid_ = facebookUid_;
                result.bitField0_ = to_bitField0_;
                onBuilt();
                return result;
            }

            @java.lang.Override
            public Builder clone() {
                return (Builder) super.clone();
            }

            @java.lang.Override
            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return (Builder) super.setField(field, value);
            }

            @java.lang.Override
            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return (Builder) super.clearField(field);
            }

            @java.lang.Override
            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return (Builder) super.clearOneof(oneof);
            }

            @java.lang.Override
            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, java.lang.Object value) {
                return (Builder) super.setRepeatedField(field, index, value);
            }

            @java.lang.Override
            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return (Builder) super.addRepeatedField(field, value);
            }

            @java.lang.Override
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof Social.DecorationData) {
                    return mergeFrom((Social.DecorationData) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(Social.DecorationData other) {
                if (other == Social.DecorationData.getDefaultInstance()) return this;
                if (other.hasUsername()) {
                    bitField0_ |= 0x00000001;
                    username_ = other.username_;
                    onChanged();
                }
                if (other.hasFullName()) {
                    bitField0_ |= 0x00000002;
                    fullName_ = other.fullName_;
                    onChanged();
                }
                if (other.hasImageUrl()) {
                    bitField0_ |= 0x00000004;
                    imageUrl_ = other.imageUrl_;
                    onChanged();
                }
                if (other.hasLargeImageUrl()) {
                    bitField0_ |= 0x00000008;
                    largeImageUrl_ = other.largeImageUrl_;
                    onChanged();
                }
                if (other.hasFirstName()) {
                    bitField0_ |= 0x00000010;
                    firstName_ = other.firstName_;
                    onChanged();
                }
                if (other.hasLastName()) {
                    bitField0_ |= 0x00000020;
                    lastName_ = other.lastName_;
                    onChanged();
                }
                if (other.hasFacebookUid()) {
                    bitField0_ |= 0x00000040;
                    facebookUid_ = other.facebookUid_;
                    onChanged();
                }
                this.mergeUnknownFields(other.unknownFields);
                onChanged();
                return this;
            }

            @java.lang.Override
            public final boolean isInitialized() {
                return true;
            }

            @java.lang.Override
            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                Social.DecorationData parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (Social.DecorationData) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            /**
             * <code>optional string username = 1;</code>
             */
            public boolean hasUsername() {
                return ((bitField0_ & 0x00000001) == 0x00000001);
            }

            /**
             * <code>optional string username = 1;</code>
             */
            public java.lang.String getUsername() {
                java.lang.Object ref = username_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    if (bs.isValidUtf8()) {
                        username_ = s;
                    }
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <code>optional string username = 1;</code>
             */
            public Builder setUsername(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000001;
                username_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional string username = 1;</code>
             */
            public com.google.protobuf.ByteString
            getUsernameBytes() {
                java.lang.Object ref = username_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    username_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>optional string username = 1;</code>
             */
            public Builder setUsernameBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000001;
                username_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional string username = 1;</code>
             */
            public Builder clearUsername() {
                bitField0_ = (bitField0_ & ~0x00000001);
                username_ = getDefaultInstance().getUsername();
                onChanged();
                return this;
            }

            /**
             * <code>optional string full_name = 2;</code>
             */
            public boolean hasFullName() {
                return ((bitField0_ & 0x00000002) == 0x00000002);
            }

            /**
             * <code>optional string full_name = 2;</code>
             */
            public java.lang.String getFullName() {
                java.lang.Object ref = fullName_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    if (bs.isValidUtf8()) {
                        fullName_ = s;
                    }
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <code>optional string full_name = 2;</code>
             */
            public Builder setFullName(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000002;
                fullName_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional string full_name = 2;</code>
             */
            public com.google.protobuf.ByteString
            getFullNameBytes() {
                java.lang.Object ref = fullName_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    fullName_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>optional string full_name = 2;</code>
             */
            public Builder setFullNameBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000002;
                fullName_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional string full_name = 2;</code>
             */
            public Builder clearFullName() {
                bitField0_ = (bitField0_ & ~0x00000002);
                fullName_ = getDefaultInstance().getFullName();
                onChanged();
                return this;
            }

            /**
             * <code>optional string image_url = 3;</code>
             */
            public boolean hasImageUrl() {
                return ((bitField0_ & 0x00000004) == 0x00000004);
            }

            /**
             * <code>optional string image_url = 3;</code>
             */
            public java.lang.String getImageUrl() {
                java.lang.Object ref = imageUrl_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    if (bs.isValidUtf8()) {
                        imageUrl_ = s;
                    }
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <code>optional string image_url = 3;</code>
             */
            public Builder setImageUrl(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000004;
                imageUrl_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional string image_url = 3;</code>
             */
            public com.google.protobuf.ByteString
            getImageUrlBytes() {
                java.lang.Object ref = imageUrl_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    imageUrl_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>optional string image_url = 3;</code>
             */
            public Builder setImageUrlBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000004;
                imageUrl_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional string image_url = 3;</code>
             */
            public Builder clearImageUrl() {
                bitField0_ = (bitField0_ & ~0x00000004);
                imageUrl_ = getDefaultInstance().getImageUrl();
                onChanged();
                return this;
            }

            /**
             * <code>optional string large_image_url = 5;</code>
             */
            public boolean hasLargeImageUrl() {
                return ((bitField0_ & 0x00000008) == 0x00000008);
            }

            /**
             * <code>optional string large_image_url = 5;</code>
             */
            public java.lang.String getLargeImageUrl() {
                java.lang.Object ref = largeImageUrl_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    if (bs.isValidUtf8()) {
                        largeImageUrl_ = s;
                    }
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <code>optional string large_image_url = 5;</code>
             */
            public Builder setLargeImageUrl(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000008;
                largeImageUrl_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional string large_image_url = 5;</code>
             */
            public com.google.protobuf.ByteString
            getLargeImageUrlBytes() {
                java.lang.Object ref = largeImageUrl_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    largeImageUrl_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>optional string large_image_url = 5;</code>
             */
            public Builder setLargeImageUrlBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000008;
                largeImageUrl_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional string large_image_url = 5;</code>
             */
            public Builder clearLargeImageUrl() {
                bitField0_ = (bitField0_ & ~0x00000008);
                largeImageUrl_ = getDefaultInstance().getLargeImageUrl();
                onChanged();
                return this;
            }

            /**
             * <code>optional string first_name = 6;</code>
             */
            public boolean hasFirstName() {
                return ((bitField0_ & 0x00000010) == 0x00000010);
            }

            /**
             * <code>optional string first_name = 6;</code>
             */
            public java.lang.String getFirstName() {
                java.lang.Object ref = firstName_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    if (bs.isValidUtf8()) {
                        firstName_ = s;
                    }
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <code>optional string first_name = 6;</code>
             */
            public Builder setFirstName(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000010;
                firstName_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional string first_name = 6;</code>
             */
            public com.google.protobuf.ByteString
            getFirstNameBytes() {
                java.lang.Object ref = firstName_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    firstName_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>optional string first_name = 6;</code>
             */
            public Builder setFirstNameBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000010;
                firstName_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional string first_name = 6;</code>
             */
            public Builder clearFirstName() {
                bitField0_ = (bitField0_ & ~0x00000010);
                firstName_ = getDefaultInstance().getFirstName();
                onChanged();
                return this;
            }

            /**
             * <code>optional string last_name = 7;</code>
             */
            public boolean hasLastName() {
                return ((bitField0_ & 0x00000020) == 0x00000020);
            }

            /**
             * <code>optional string last_name = 7;</code>
             */
            public java.lang.String getLastName() {
                java.lang.Object ref = lastName_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    if (bs.isValidUtf8()) {
                        lastName_ = s;
                    }
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <code>optional string last_name = 7;</code>
             */
            public Builder setLastName(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000020;
                lastName_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional string last_name = 7;</code>
             */
            public com.google.protobuf.ByteString
            getLastNameBytes() {
                java.lang.Object ref = lastName_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    lastName_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>optional string last_name = 7;</code>
             */
            public Builder setLastNameBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000020;
                lastName_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional string last_name = 7;</code>
             */
            public Builder clearLastName() {
                bitField0_ = (bitField0_ & ~0x00000020);
                lastName_ = getDefaultInstance().getLastName();
                onChanged();
                return this;
            }

            /**
             * <code>optional string facebook_uid = 8;</code>
             */
            public boolean hasFacebookUid() {
                return ((bitField0_ & 0x00000040) == 0x00000040);
            }

            /**
             * <code>optional string facebook_uid = 8;</code>
             */
            public java.lang.String getFacebookUid() {
                java.lang.Object ref = facebookUid_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    if (bs.isValidUtf8()) {
                        facebookUid_ = s;
                    }
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <code>optional string facebook_uid = 8;</code>
             */
            public Builder setFacebookUid(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000040;
                facebookUid_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional string facebook_uid = 8;</code>
             */
            public com.google.protobuf.ByteString
            getFacebookUidBytes() {
                java.lang.Object ref = facebookUid_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    facebookUid_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>optional string facebook_uid = 8;</code>
             */
            public Builder setFacebookUidBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000040;
                facebookUid_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional string facebook_uid = 8;</code>
             */
            public Builder clearFacebookUid() {
                bitField0_ = (bitField0_ & ~0x00000040);
                facebookUid_ = getDefaultInstance().getFacebookUid();
                onChanged();
                return this;
            }

            @java.lang.Override
            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.setUnknownFields(unknownFields);
            }

            @java.lang.Override
            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.mergeUnknownFields(unknownFields);
            }


            // @@protoc_insertion_point(builder_scope:DecorationData)
        }

    }

    // @@protoc_insertion_point(outer_class_scope)
}
