// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: session.proto

package spotify.player.proto.transfer;

public final class SessionOuterClass {
    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_spotify_player_proto_transfer_Session_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_spotify_player_proto_transfer_Session_fieldAccessorTable;
    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static {
        java.lang.String[] descriptorData = {
                "\n\rsession.proto\022\035spotify.player.proto.tr" +
                        "ansfer\032\rcontext.proto\032\034context_player_op" +
                        "tions.proto\032\021play_origin.proto\"\323\001\n\007Sessi" +
                        "on\0225\n\013play_origin\030\001 \001(\0132 .spotify.player" +
                        ".proto.PlayOrigin\022.\n\007context\030\002 \001(\0132\035.spo" +
                        "tify.player.proto.Context\022\023\n\013current_uid" +
                        "\030\003 \001(\t\022L\n\020option_overrides\030\004 \001(\01322.spoti" +
                        "fy.player.proto.ContextPlayerOptionOverr" +
                        "idesB\002H\002"
        };
        com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
                new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
                    public com.google.protobuf.ExtensionRegistry assignDescriptors(
                            com.google.protobuf.Descriptors.FileDescriptor root) {
                        descriptor = root;
                        return null;
                    }
                };
        com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{
                                spotify.player.proto.ContextOuterClass.getDescriptor(),
                                spotify.player.proto.ContextPlayerOptionsOuterClass.getDescriptor(),
                                spotify.player.proto.PlayOriginOuterClass.getDescriptor(),
                        }, assigner);
        internal_static_spotify_player_proto_transfer_Session_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_spotify_player_proto_transfer_Session_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_spotify_player_proto_transfer_Session_descriptor,
                new java.lang.String[]{"PlayOrigin", "Context", "CurrentUid", "OptionOverrides",});
        spotify.player.proto.ContextOuterClass.getDescriptor();
        spotify.player.proto.ContextPlayerOptionsOuterClass.getDescriptor();
        spotify.player.proto.PlayOriginOuterClass.getDescriptor();
    }

    private SessionOuterClass() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }

    public interface SessionOrBuilder extends
            // @@protoc_insertion_point(interface_extends:spotify.player.proto.transfer.Session)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>optional .spotify.player.proto.PlayOrigin play_origin = 1;</code>
         */
        boolean hasPlayOrigin();

        /**
         * <code>optional .spotify.player.proto.PlayOrigin play_origin = 1;</code>
         */
        spotify.player.proto.PlayOriginOuterClass.PlayOrigin getPlayOrigin();

        /**
         * <code>optional .spotify.player.proto.PlayOrigin play_origin = 1;</code>
         */
        spotify.player.proto.PlayOriginOuterClass.PlayOriginOrBuilder getPlayOriginOrBuilder();

        /**
         * <code>optional .spotify.player.proto.Context context = 2;</code>
         */
        boolean hasContext();

        /**
         * <code>optional .spotify.player.proto.Context context = 2;</code>
         */
        spotify.player.proto.ContextOuterClass.Context getContext();

        /**
         * <code>optional .spotify.player.proto.Context context = 2;</code>
         */
        spotify.player.proto.ContextOuterClass.ContextOrBuilder getContextOrBuilder();

        /**
         * <code>optional string current_uid = 3;</code>
         */
        boolean hasCurrentUid();

        /**
         * <code>optional string current_uid = 3;</code>
         */
        java.lang.String getCurrentUid();

        /**
         * <code>optional string current_uid = 3;</code>
         */
        com.google.protobuf.ByteString
        getCurrentUidBytes();

        /**
         * <code>optional .spotify.player.proto.ContextPlayerOptionOverrides option_overrides = 4;</code>
         */
        boolean hasOptionOverrides();

        /**
         * <code>optional .spotify.player.proto.ContextPlayerOptionOverrides option_overrides = 4;</code>
         */
        spotify.player.proto.ContextPlayerOptionsOuterClass.ContextPlayerOptionOverrides getOptionOverrides();

        /**
         * <code>optional .spotify.player.proto.ContextPlayerOptionOverrides option_overrides = 4;</code>
         */
        spotify.player.proto.ContextPlayerOptionsOuterClass.ContextPlayerOptionOverridesOrBuilder getOptionOverridesOrBuilder();
    }

    /**
     * Protobuf type {@code spotify.player.proto.transfer.Session}
     */
    public static final class Session extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:spotify.player.proto.transfer.Session)
            SessionOrBuilder {
        public static final int PLAY_ORIGIN_FIELD_NUMBER = 1;
        public static final int CONTEXT_FIELD_NUMBER = 2;
        public static final int CURRENT_UID_FIELD_NUMBER = 3;
        public static final int OPTION_OVERRIDES_FIELD_NUMBER = 4;
        private static final long serialVersionUID = 0L;
        // @@protoc_insertion_point(class_scope:spotify.player.proto.transfer.Session)
        private static final spotify.player.proto.transfer.SessionOuterClass.Session DEFAULT_INSTANCE;
        @java.lang.Deprecated
        public static final com.google.protobuf.Parser<Session>
                PARSER = new com.google.protobuf.AbstractParser<Session>() {
            @java.lang.Override
            public Session parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                Builder builder = newBuilder();
                try {
                    builder.mergeFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    throw e.setUnfinishedMessage(builder.buildPartial());
                } catch (java.io.IOException e) {
                    throw new com.google.protobuf.InvalidProtocolBufferException(
                            e.getMessage()).setUnfinishedMessage(
                            builder.buildPartial());
                }
                return builder.buildPartial();
            }
        };

        static {
            DEFAULT_INSTANCE = new spotify.player.proto.transfer.SessionOuterClass.Session();
        }

        private int bitField0_;
        private spotify.player.proto.PlayOriginOuterClass.PlayOrigin playOrigin_;
        private spotify.player.proto.ContextOuterClass.Context context_;
        private volatile java.lang.Object currentUid_;
        private spotify.player.proto.ContextPlayerOptionsOuterClass.ContextPlayerOptionOverrides optionOverrides_;

        // Use Session.newBuilder() to construct.
        private Session(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }

        private Session() {
            currentUid_ = "";
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return spotify.player.proto.transfer.SessionOuterClass.internal_static_spotify_player_proto_transfer_Session_descriptor;
        }

        public static spotify.player.proto.transfer.SessionOuterClass.Session parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static spotify.player.proto.transfer.SessionOuterClass.Session parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static spotify.player.proto.transfer.SessionOuterClass.Session parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static spotify.player.proto.transfer.SessionOuterClass.Session parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static spotify.player.proto.transfer.SessionOuterClass.Session parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static spotify.player.proto.transfer.SessionOuterClass.Session parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static spotify.player.proto.transfer.SessionOuterClass.Session parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static spotify.player.proto.transfer.SessionOuterClass.Session parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static spotify.player.proto.transfer.SessionOuterClass.Session parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }

        public static spotify.player.proto.transfer.SessionOuterClass.Session parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static spotify.player.proto.transfer.SessionOuterClass.Session parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static spotify.player.proto.transfer.SessionOuterClass.Session parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(spotify.player.proto.transfer.SessionOuterClass.Session prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        public static spotify.player.proto.transfer.SessionOuterClass.Session getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        public static com.google.protobuf.Parser<Session> parser() {
            return PARSER;
        }

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return this.unknownFields;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return spotify.player.proto.transfer.SessionOuterClass.internal_static_spotify_player_proto_transfer_Session_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            spotify.player.proto.transfer.SessionOuterClass.Session.class, spotify.player.proto.transfer.SessionOuterClass.Session.Builder.class);
        }

        /**
         * <code>optional .spotify.player.proto.PlayOrigin play_origin = 1;</code>
         */
        public boolean hasPlayOrigin() {
            return ((bitField0_ & 0x00000001) == 0x00000001);
        }

        /**
         * <code>optional .spotify.player.proto.PlayOrigin play_origin = 1;</code>
         */
        public spotify.player.proto.PlayOriginOuterClass.PlayOrigin getPlayOrigin() {
            return playOrigin_ == null ? spotify.player.proto.PlayOriginOuterClass.PlayOrigin.getDefaultInstance() : playOrigin_;
        }

        /**
         * <code>optional .spotify.player.proto.PlayOrigin play_origin = 1;</code>
         */
        public spotify.player.proto.PlayOriginOuterClass.PlayOriginOrBuilder getPlayOriginOrBuilder() {
            return playOrigin_ == null ? spotify.player.proto.PlayOriginOuterClass.PlayOrigin.getDefaultInstance() : playOrigin_;
        }

        /**
         * <code>optional .spotify.player.proto.Context context = 2;</code>
         */
        public boolean hasContext() {
            return ((bitField0_ & 0x00000002) == 0x00000002);
        }

        /**
         * <code>optional .spotify.player.proto.Context context = 2;</code>
         */
        public spotify.player.proto.ContextOuterClass.Context getContext() {
            return context_ == null ? spotify.player.proto.ContextOuterClass.Context.getDefaultInstance() : context_;
        }

        /**
         * <code>optional .spotify.player.proto.Context context = 2;</code>
         */
        public spotify.player.proto.ContextOuterClass.ContextOrBuilder getContextOrBuilder() {
            return context_ == null ? spotify.player.proto.ContextOuterClass.Context.getDefaultInstance() : context_;
        }

        /**
         * <code>optional string current_uid = 3;</code>
         */
        public boolean hasCurrentUid() {
            return ((bitField0_ & 0x00000004) == 0x00000004);
        }

        /**
         * <code>optional string current_uid = 3;</code>
         */
        public java.lang.String getCurrentUid() {
            java.lang.Object ref = currentUid_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                if (bs.isValidUtf8()) {
                    currentUid_ = s;
                }
                return s;
            }
        }

        /**
         * <code>optional string current_uid = 3;</code>
         */
        public com.google.protobuf.ByteString
        getCurrentUidBytes() {
            java.lang.Object ref = currentUid_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                currentUid_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>optional .spotify.player.proto.ContextPlayerOptionOverrides option_overrides = 4;</code>
         */
        public boolean hasOptionOverrides() {
            return ((bitField0_ & 0x00000008) == 0x00000008);
        }

        /**
         * <code>optional .spotify.player.proto.ContextPlayerOptionOverrides option_overrides = 4;</code>
         */
        public spotify.player.proto.ContextPlayerOptionsOuterClass.ContextPlayerOptionOverrides getOptionOverrides() {
            return optionOverrides_ == null ? spotify.player.proto.ContextPlayerOptionsOuterClass.ContextPlayerOptionOverrides.getDefaultInstance() : optionOverrides_;
        }

        /**
         * <code>optional .spotify.player.proto.ContextPlayerOptionOverrides option_overrides = 4;</code>
         */
        public spotify.player.proto.ContextPlayerOptionsOuterClass.ContextPlayerOptionOverridesOrBuilder getOptionOverridesOrBuilder() {
            return optionOverrides_ == null ? spotify.player.proto.ContextPlayerOptionsOuterClass.ContextPlayerOptionOverrides.getDefaultInstance() : optionOverrides_;
        }

        @java.lang.Override
        public Builder newBuilderForType() {
            return newBuilder();
        }

        @java.lang.Override
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<Session> getParserForType() {
            return PARSER;
        }

        @java.lang.Override
        public spotify.player.proto.transfer.SessionOuterClass.Session getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

        /**
         * Protobuf type {@code spotify.player.proto.transfer.Session}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:spotify.player.proto.transfer.Session)
                spotify.player.proto.transfer.SessionOuterClass.SessionOrBuilder {
            private int bitField0_;
            private spotify.player.proto.PlayOriginOuterClass.PlayOrigin playOrigin_ = null;
            private com.google.protobuf.SingleFieldBuilderV3<
                    spotify.player.proto.PlayOriginOuterClass.PlayOrigin, spotify.player.proto.PlayOriginOuterClass.PlayOrigin.Builder, spotify.player.proto.PlayOriginOuterClass.PlayOriginOrBuilder> playOriginBuilder_;
            private spotify.player.proto.ContextOuterClass.Context context_ = null;
            private com.google.protobuf.SingleFieldBuilderV3<
                    spotify.player.proto.ContextOuterClass.Context, spotify.player.proto.ContextOuterClass.Context.Builder, spotify.player.proto.ContextOuterClass.ContextOrBuilder> contextBuilder_;
            private java.lang.Object currentUid_ = "";
            private spotify.player.proto.ContextPlayerOptionsOuterClass.ContextPlayerOptionOverrides optionOverrides_ = null;
            private com.google.protobuf.SingleFieldBuilderV3<
                    spotify.player.proto.ContextPlayerOptionsOuterClass.ContextPlayerOptionOverrides, spotify.player.proto.ContextPlayerOptionsOuterClass.ContextPlayerOptionOverrides.Builder, spotify.player.proto.ContextPlayerOptionsOuterClass.ContextPlayerOptionOverridesOrBuilder> optionOverridesBuilder_;

            // Construct using spotify.player.proto.transfer.SessionOuterClass.Session.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return spotify.player.proto.transfer.SessionOuterClass.internal_static_spotify_player_proto_transfer_Session_descriptor;
            }

            @java.lang.Override
            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return spotify.player.proto.transfer.SessionOuterClass.internal_static_spotify_player_proto_transfer_Session_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                spotify.player.proto.transfer.SessionOuterClass.Session.class, spotify.player.proto.transfer.SessionOuterClass.Session.Builder.class);
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                    getPlayOriginFieldBuilder();
                    getContextFieldBuilder();
                    getOptionOverridesFieldBuilder();
                }
            }

            @java.lang.Override
            public Builder clear() {
                super.clear();
                if (playOriginBuilder_ == null) {
                    playOrigin_ = null;
                } else {
                    playOriginBuilder_.clear();
                }
                bitField0_ = (bitField0_ & ~0x00000001);
                if (contextBuilder_ == null) {
                    context_ = null;
                } else {
                    contextBuilder_.clear();
                }
                bitField0_ = (bitField0_ & ~0x00000002);
                currentUid_ = "";
                bitField0_ = (bitField0_ & ~0x00000004);
                if (optionOverridesBuilder_ == null) {
                    optionOverrides_ = null;
                } else {
                    optionOverridesBuilder_.clear();
                }
                bitField0_ = (bitField0_ & ~0x00000008);
                return this;
            }

            @java.lang.Override
            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return spotify.player.proto.transfer.SessionOuterClass.internal_static_spotify_player_proto_transfer_Session_descriptor;
            }

            @java.lang.Override
            public spotify.player.proto.transfer.SessionOuterClass.Session getDefaultInstanceForType() {
                return spotify.player.proto.transfer.SessionOuterClass.Session.getDefaultInstance();
            }

            @java.lang.Override
            public spotify.player.proto.transfer.SessionOuterClass.Session build() {
                spotify.player.proto.transfer.SessionOuterClass.Session result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @java.lang.Override
            public spotify.player.proto.transfer.SessionOuterClass.Session buildPartial() {
                spotify.player.proto.transfer.SessionOuterClass.Session result = new spotify.player.proto.transfer.SessionOuterClass.Session(this);
                int from_bitField0_ = bitField0_;
                int to_bitField0_ = 0;
                if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
                    to_bitField0_ |= 0x00000001;
                }
                if (playOriginBuilder_ == null) {
                    result.playOrigin_ = playOrigin_;
                } else {
                    result.playOrigin_ = playOriginBuilder_.build();
                }
                if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
                    to_bitField0_ |= 0x00000002;
                }
                if (contextBuilder_ == null) {
                    result.context_ = context_;
                } else {
                    result.context_ = contextBuilder_.build();
                }
                if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
                    to_bitField0_ |= 0x00000004;
                }
                result.currentUid_ = currentUid_;
                if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
                    to_bitField0_ |= 0x00000008;
                }
                if (optionOverridesBuilder_ == null) {
                    result.optionOverrides_ = optionOverrides_;
                } else {
                    result.optionOverrides_ = optionOverridesBuilder_.build();
                }
                result.bitField0_ = to_bitField0_;
                onBuilt();
                return result;
            }

            @java.lang.Override
            public Builder clone() {
                return super.clone();
            }

            @java.lang.Override
            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return super.setField(field, value);
            }

            @java.lang.Override
            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return super.clearField(field);
            }

            @java.lang.Override
            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return super.clearOneof(oneof);
            }

            @java.lang.Override
            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, java.lang.Object value) {
                return super.setRepeatedField(field, index, value);
            }

            @java.lang.Override
            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return super.addRepeatedField(field, value);
            }

            /**
             * <code>optional .spotify.player.proto.PlayOrigin play_origin = 1;</code>
             */
            public boolean hasPlayOrigin() {
                return ((bitField0_ & 0x00000001) == 0x00000001);
            }

            /**
             * <code>optional .spotify.player.proto.PlayOrigin play_origin = 1;</code>
             */
            public spotify.player.proto.PlayOriginOuterClass.PlayOrigin getPlayOrigin() {
                if (playOriginBuilder_ == null) {
                    return playOrigin_ == null ? spotify.player.proto.PlayOriginOuterClass.PlayOrigin.getDefaultInstance() : playOrigin_;
                } else {
                    return playOriginBuilder_.getMessage();
                }
            }

            /**
             * <code>optional .spotify.player.proto.PlayOrigin play_origin = 1;</code>
             */
            public Builder setPlayOrigin(spotify.player.proto.PlayOriginOuterClass.PlayOrigin value) {
                if (playOriginBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    playOrigin_ = value;
                    onChanged();
                } else {
                    playOriginBuilder_.setMessage(value);
                }
                bitField0_ |= 0x00000001;
                return this;
            }

            /**
             * <code>optional .spotify.player.proto.PlayOrigin play_origin = 1;</code>
             */
            public Builder setPlayOrigin(
                    spotify.player.proto.PlayOriginOuterClass.PlayOrigin.Builder builderForValue) {
                if (playOriginBuilder_ == null) {
                    playOrigin_ = builderForValue.build();
                    onChanged();
                } else {
                    playOriginBuilder_.setMessage(builderForValue.build());
                }
                bitField0_ |= 0x00000001;
                return this;
            }

            /**
             * <code>optional .spotify.player.proto.PlayOrigin play_origin = 1;</code>
             */
            public Builder mergePlayOrigin(spotify.player.proto.PlayOriginOuterClass.PlayOrigin value) {
                if (playOriginBuilder_ == null) {
                    if (((bitField0_ & 0x00000001) == 0x00000001) &&
                            playOrigin_ != null &&
                            playOrigin_ != spotify.player.proto.PlayOriginOuterClass.PlayOrigin.getDefaultInstance()) {
                        playOrigin_ =
                                spotify.player.proto.PlayOriginOuterClass.PlayOrigin.newBuilder(playOrigin_).mergeFrom(value).buildPartial();
                    } else {
                        playOrigin_ = value;
                    }
                    onChanged();
                } else {
                    playOriginBuilder_.mergeFrom(value);
                }
                bitField0_ |= 0x00000001;
                return this;
            }

            /**
             * <code>optional .spotify.player.proto.PlayOrigin play_origin = 1;</code>
             */
            public Builder clearPlayOrigin() {
                if (playOriginBuilder_ == null) {
                    playOrigin_ = null;
                    onChanged();
                } else {
                    playOriginBuilder_.clear();
                }
                bitField0_ = (bitField0_ & ~0x00000001);
                return this;
            }

            /**
             * <code>optional .spotify.player.proto.PlayOrigin play_origin = 1;</code>
             */
            public spotify.player.proto.PlayOriginOuterClass.PlayOrigin.Builder getPlayOriginBuilder() {
                bitField0_ |= 0x00000001;
                onChanged();
                return getPlayOriginFieldBuilder().getBuilder();
            }

            /**
             * <code>optional .spotify.player.proto.PlayOrigin play_origin = 1;</code>
             */
            public spotify.player.proto.PlayOriginOuterClass.PlayOriginOrBuilder getPlayOriginOrBuilder() {
                if (playOriginBuilder_ != null) {
                    return playOriginBuilder_.getMessageOrBuilder();
                } else {
                    return playOrigin_ == null ?
                            spotify.player.proto.PlayOriginOuterClass.PlayOrigin.getDefaultInstance() : playOrigin_;
                }
            }

            /**
             * <code>optional .spotify.player.proto.PlayOrigin play_origin = 1;</code>
             */
            private com.google.protobuf.SingleFieldBuilderV3<
                    spotify.player.proto.PlayOriginOuterClass.PlayOrigin, spotify.player.proto.PlayOriginOuterClass.PlayOrigin.Builder, spotify.player.proto.PlayOriginOuterClass.PlayOriginOrBuilder>
            getPlayOriginFieldBuilder() {
                if (playOriginBuilder_ == null) {
                    playOriginBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
                            spotify.player.proto.PlayOriginOuterClass.PlayOrigin, spotify.player.proto.PlayOriginOuterClass.PlayOrigin.Builder, spotify.player.proto.PlayOriginOuterClass.PlayOriginOrBuilder>(
                            getPlayOrigin(),
                            getParentForChildren(),
                            isClean());
                    playOrigin_ = null;
                }
                return playOriginBuilder_;
            }

            /**
             * <code>optional .spotify.player.proto.Context context = 2;</code>
             */
            public boolean hasContext() {
                return ((bitField0_ & 0x00000002) == 0x00000002);
            }

            /**
             * <code>optional .spotify.player.proto.Context context = 2;</code>
             */
            public spotify.player.proto.ContextOuterClass.Context getContext() {
                if (contextBuilder_ == null) {
                    return context_ == null ? spotify.player.proto.ContextOuterClass.Context.getDefaultInstance() : context_;
                } else {
                    return contextBuilder_.getMessage();
                }
            }

            /**
             * <code>optional .spotify.player.proto.Context context = 2;</code>
             */
            public Builder setContext(spotify.player.proto.ContextOuterClass.Context value) {
                if (contextBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    context_ = value;
                    onChanged();
                } else {
                    contextBuilder_.setMessage(value);
                }
                bitField0_ |= 0x00000002;
                return this;
            }

            /**
             * <code>optional .spotify.player.proto.Context context = 2;</code>
             */
            public Builder setContext(
                    spotify.player.proto.ContextOuterClass.Context.Builder builderForValue) {
                if (contextBuilder_ == null) {
                    context_ = builderForValue.build();
                    onChanged();
                } else {
                    contextBuilder_.setMessage(builderForValue.build());
                }
                bitField0_ |= 0x00000002;
                return this;
            }

            /**
             * <code>optional .spotify.player.proto.Context context = 2;</code>
             */
            public Builder mergeContext(spotify.player.proto.ContextOuterClass.Context value) {
                if (contextBuilder_ == null) {
                    if (((bitField0_ & 0x00000002) == 0x00000002) &&
                            context_ != null &&
                            context_ != spotify.player.proto.ContextOuterClass.Context.getDefaultInstance()) {
                        context_ =
                                spotify.player.proto.ContextOuterClass.Context.newBuilder(context_).mergeFrom(value).buildPartial();
                    } else {
                        context_ = value;
                    }
                    onChanged();
                } else {
                    contextBuilder_.mergeFrom(value);
                }
                bitField0_ |= 0x00000002;
                return this;
            }

            /**
             * <code>optional .spotify.player.proto.Context context = 2;</code>
             */
            public Builder clearContext() {
                if (contextBuilder_ == null) {
                    context_ = null;
                    onChanged();
                } else {
                    contextBuilder_.clear();
                }
                bitField0_ = (bitField0_ & ~0x00000002);
                return this;
            }

            /**
             * <code>optional .spotify.player.proto.Context context = 2;</code>
             */
            public spotify.player.proto.ContextOuterClass.Context.Builder getContextBuilder() {
                bitField0_ |= 0x00000002;
                onChanged();
                return getContextFieldBuilder().getBuilder();
            }

            /**
             * <code>optional .spotify.player.proto.Context context = 2;</code>
             */
            public spotify.player.proto.ContextOuterClass.ContextOrBuilder getContextOrBuilder() {
                if (contextBuilder_ != null) {
                    return contextBuilder_.getMessageOrBuilder();
                } else {
                    return context_ == null ?
                            spotify.player.proto.ContextOuterClass.Context.getDefaultInstance() : context_;
                }
            }

            /**
             * <code>optional .spotify.player.proto.Context context = 2;</code>
             */
            private com.google.protobuf.SingleFieldBuilderV3<
                    spotify.player.proto.ContextOuterClass.Context, spotify.player.proto.ContextOuterClass.Context.Builder, spotify.player.proto.ContextOuterClass.ContextOrBuilder>
            getContextFieldBuilder() {
                if (contextBuilder_ == null) {
                    contextBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
                            spotify.player.proto.ContextOuterClass.Context, spotify.player.proto.ContextOuterClass.Context.Builder, spotify.player.proto.ContextOuterClass.ContextOrBuilder>(
                            getContext(),
                            getParentForChildren(),
                            isClean());
                    context_ = null;
                }
                return contextBuilder_;
            }

            /**
             * <code>optional string current_uid = 3;</code>
             */
            public boolean hasCurrentUid() {
                return ((bitField0_ & 0x00000004) == 0x00000004);
            }

            /**
             * <code>optional string current_uid = 3;</code>
             */
            public java.lang.String getCurrentUid() {
                java.lang.Object ref = currentUid_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    if (bs.isValidUtf8()) {
                        currentUid_ = s;
                    }
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <code>optional string current_uid = 3;</code>
             */
            public Builder setCurrentUid(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000004;
                currentUid_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional string current_uid = 3;</code>
             */
            public com.google.protobuf.ByteString
            getCurrentUidBytes() {
                java.lang.Object ref = currentUid_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    currentUid_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>optional string current_uid = 3;</code>
             */
            public Builder setCurrentUidBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000004;
                currentUid_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional string current_uid = 3;</code>
             */
            public Builder clearCurrentUid() {
                bitField0_ = (bitField0_ & ~0x00000004);
                currentUid_ = getDefaultInstance().getCurrentUid();
                onChanged();
                return this;
            }

            /**
             * <code>optional .spotify.player.proto.ContextPlayerOptionOverrides option_overrides = 4;</code>
             */
            public boolean hasOptionOverrides() {
                return ((bitField0_ & 0x00000008) == 0x00000008);
            }

            /**
             * <code>optional .spotify.player.proto.ContextPlayerOptionOverrides option_overrides = 4;</code>
             */
            public spotify.player.proto.ContextPlayerOptionsOuterClass.ContextPlayerOptionOverrides getOptionOverrides() {
                if (optionOverridesBuilder_ == null) {
                    return optionOverrides_ == null ? spotify.player.proto.ContextPlayerOptionsOuterClass.ContextPlayerOptionOverrides.getDefaultInstance() : optionOverrides_;
                } else {
                    return optionOverridesBuilder_.getMessage();
                }
            }

            /**
             * <code>optional .spotify.player.proto.ContextPlayerOptionOverrides option_overrides = 4;</code>
             */
            public Builder setOptionOverrides(spotify.player.proto.ContextPlayerOptionsOuterClass.ContextPlayerOptionOverrides value) {
                if (optionOverridesBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    optionOverrides_ = value;
                    onChanged();
                } else {
                    optionOverridesBuilder_.setMessage(value);
                }
                bitField0_ |= 0x00000008;
                return this;
            }

            /**
             * <code>optional .spotify.player.proto.ContextPlayerOptionOverrides option_overrides = 4;</code>
             */
            public Builder setOptionOverrides(
                    spotify.player.proto.ContextPlayerOptionsOuterClass.ContextPlayerOptionOverrides.Builder builderForValue) {
                if (optionOverridesBuilder_ == null) {
                    optionOverrides_ = builderForValue.build();
                    onChanged();
                } else {
                    optionOverridesBuilder_.setMessage(builderForValue.build());
                }
                bitField0_ |= 0x00000008;
                return this;
            }

            /**
             * <code>optional .spotify.player.proto.ContextPlayerOptionOverrides option_overrides = 4;</code>
             */
            public Builder mergeOptionOverrides(spotify.player.proto.ContextPlayerOptionsOuterClass.ContextPlayerOptionOverrides value) {
                if (optionOverridesBuilder_ == null) {
                    if (((bitField0_ & 0x00000008) == 0x00000008) &&
                            optionOverrides_ != null &&
                            optionOverrides_ != spotify.player.proto.ContextPlayerOptionsOuterClass.ContextPlayerOptionOverrides.getDefaultInstance()) {
                        optionOverrides_ =
                                spotify.player.proto.ContextPlayerOptionsOuterClass.ContextPlayerOptionOverrides.newBuilder(optionOverrides_).mergeFrom(value).buildPartial();
                    } else {
                        optionOverrides_ = value;
                    }
                    onChanged();
                } else {
                    optionOverridesBuilder_.mergeFrom(value);
                }
                bitField0_ |= 0x00000008;
                return this;
            }

            /**
             * <code>optional .spotify.player.proto.ContextPlayerOptionOverrides option_overrides = 4;</code>
             */
            public Builder clearOptionOverrides() {
                if (optionOverridesBuilder_ == null) {
                    optionOverrides_ = null;
                    onChanged();
                } else {
                    optionOverridesBuilder_.clear();
                }
                bitField0_ = (bitField0_ & ~0x00000008);
                return this;
            }

            /**
             * <code>optional .spotify.player.proto.ContextPlayerOptionOverrides option_overrides = 4;</code>
             */
            public spotify.player.proto.ContextPlayerOptionsOuterClass.ContextPlayerOptionOverrides.Builder getOptionOverridesBuilder() {
                bitField0_ |= 0x00000008;
                onChanged();
                return getOptionOverridesFieldBuilder().getBuilder();
            }

            /**
             * <code>optional .spotify.player.proto.ContextPlayerOptionOverrides option_overrides = 4;</code>
             */
            public spotify.player.proto.ContextPlayerOptionsOuterClass.ContextPlayerOptionOverridesOrBuilder getOptionOverridesOrBuilder() {
                if (optionOverridesBuilder_ != null) {
                    return optionOverridesBuilder_.getMessageOrBuilder();
                } else {
                    return optionOverrides_ == null ?
                            spotify.player.proto.ContextPlayerOptionsOuterClass.ContextPlayerOptionOverrides.getDefaultInstance() : optionOverrides_;
                }
            }

            /**
             * <code>optional .spotify.player.proto.ContextPlayerOptionOverrides option_overrides = 4;</code>
             */
            private com.google.protobuf.SingleFieldBuilderV3<
                    spotify.player.proto.ContextPlayerOptionsOuterClass.ContextPlayerOptionOverrides, spotify.player.proto.ContextPlayerOptionsOuterClass.ContextPlayerOptionOverrides.Builder, spotify.player.proto.ContextPlayerOptionsOuterClass.ContextPlayerOptionOverridesOrBuilder>
            getOptionOverridesFieldBuilder() {
                if (optionOverridesBuilder_ == null) {
                    optionOverridesBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
                            spotify.player.proto.ContextPlayerOptionsOuterClass.ContextPlayerOptionOverrides, spotify.player.proto.ContextPlayerOptionsOuterClass.ContextPlayerOptionOverrides.Builder, spotify.player.proto.ContextPlayerOptionsOuterClass.ContextPlayerOptionOverridesOrBuilder>(
                            getOptionOverrides(),
                            getParentForChildren(),
                            isClean());
                    optionOverrides_ = null;
                }
                return optionOverridesBuilder_;
            }

            @java.lang.Override
            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.setUnknownFields(unknownFields);
            }

            @java.lang.Override
            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.mergeUnknownFields(unknownFields);
            }


            // @@protoc_insertion_point(builder_scope:spotify.player.proto.transfer.Session)
        }

    }

    // @@protoc_insertion_point(outer_class_scope)
}
