// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: playlist4issues.proto

package org.librespot.spotify.proto;

@SuppressWarnings("ALL")
public final class Playlist4Issues {
    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_ClientIssue_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_ClientIssue_fieldAccessorTable;
    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_ClientResolveAction_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_ClientResolveAction_fieldAccessorTable;
    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static {
        java.lang.String[] descriptorData = {
                "\n\025playlist4issues.proto\"\372\002\n\013ClientIssue\022" +
                        "!\n\005level\030\001 \001(\0162\022.ClientIssue.Level\022\037\n\004co" +
                        "de\030\002 \001(\0162\021.ClientIssue.Code\022\023\n\013repeatCou" +
                        "nt\030\003 \001(\005\"q\n\005Level\022\021\n\rLEVEL_UNKNOWN\020\000\022\017\n\013" +
                        "LEVEL_DEBUG\020\001\022\016\n\nLEVEL_INFO\020\002\022\020\n\014LEVEL_N" +
                        "OTICE\020\003\022\021\n\rLEVEL_WARNING\020\004\022\017\n\013LEVEL_ERRO" +
                        "R\020\005\"\236\001\n\004Code\022\020\n\014CODE_UNKNOWN\020\000\022\034\n\030CODE_I" +
                        "NDEX_OUT_OF_BOUNDS\020\001\022\031\n\025CODE_VERSION_MIS" +
                        "MATCH\020\002\022\026\n\022CODE_CACHED_CHANGE\020\003\022\027\n\023CODE_" +
                        "OFFLINE_CHANGE\020\004\022\032\n\026CODE_CONCURRENT_CHAN" +
                        "GE\020\005\"\345\002\n\023ClientResolveAction\022\'\n\004code\030\001 \001" +
                        "(\0162\031.ClientResolveAction.Code\0221\n\tinitiat" +
                        "or\030\002 \001(\0162\036.ClientResolveAction.Initiator" +
                        "\"\241\001\n\004Code\022\020\n\014CODE_UNKNOWN\020\000\022\022\n\016CODE_NO_A" +
                        "CTION\020\001\022\016\n\nCODE_RETRY\020\002\022\017\n\013CODE_RELOAD\020\003" +
                        "\022\036\n\032CODE_DISCARD_LOCAL_CHANGES\020\004\022\022\n\016CODE" +
                        "_SEND_DUMP\020\005\022\036\n\032CODE_DISPLAY_ERROR_MESSA" +
                        "GE\020\006\"N\n\tInitiator\022\025\n\021INITIATOR_UNKNOWN\020\000" +
                        "\022\024\n\020INITIATOR_SERVER\020\001\022\024\n\020INITIATOR_CLIE" +
                        "NT\020\002"
        };
        com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
                new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
                    public com.google.protobuf.ExtensionRegistry assignDescriptors(
                            com.google.protobuf.Descriptors.FileDescriptor root) {
                        descriptor = root;
                        return null;
                    }
                };
        com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{
                        }, assigner);
        internal_static_ClientIssue_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_ClientIssue_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_ClientIssue_descriptor,
                new java.lang.String[]{"Level", "Code", "RepeatCount",});
        internal_static_ClientResolveAction_descriptor =
                getDescriptor().getMessageTypes().get(1);
        internal_static_ClientResolveAction_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_ClientResolveAction_descriptor,
                new java.lang.String[]{"Code", "Initiator",});
    }

    private Playlist4Issues() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }

    public interface ClientIssueOrBuilder extends
            // @@protoc_insertion_point(interface_extends:ClientIssue)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>optional .ClientIssue.Level level = 1;</code>
         */
        boolean hasLevel();

        /**
         * <code>optional .ClientIssue.Level level = 1;</code>
         */
        Playlist4Issues.ClientIssue.Level getLevel();

        /**
         * <code>optional .ClientIssue.Code code = 2;</code>
         */
        boolean hasCode();

        /**
         * <code>optional .ClientIssue.Code code = 2;</code>
         */
        Playlist4Issues.ClientIssue.Code getCode();

        /**
         * <code>optional int32 repeatCount = 3;</code>
         */
        boolean hasRepeatCount();

        /**
         * <code>optional int32 repeatCount = 3;</code>
         */
        int getRepeatCount();
    }

    public interface ClientResolveActionOrBuilder extends
            // @@protoc_insertion_point(interface_extends:ClientResolveAction)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>optional .ClientResolveAction.Code code = 1;</code>
         */
        boolean hasCode();

        /**
         * <code>optional .ClientResolveAction.Code code = 1;</code>
         */
        Playlist4Issues.ClientResolveAction.Code getCode();

        /**
         * <code>optional .ClientResolveAction.Initiator initiator = 2;</code>
         */
        boolean hasInitiator();

        /**
         * <code>optional .ClientResolveAction.Initiator initiator = 2;</code>
         */
        Playlist4Issues.ClientResolveAction.Initiator getInitiator();
    }

    /**
     * Protobuf type {@code ClientIssue}
     */
    public static final class ClientIssue extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:ClientIssue)
            ClientIssueOrBuilder {
        public static final int LEVEL_FIELD_NUMBER = 1;
        public static final int CODE_FIELD_NUMBER = 2;
        public static final int REPEATCOUNT_FIELD_NUMBER = 3;
        @java.lang.Deprecated
        public static final com.google.protobuf.Parser<ClientIssue>
                PARSER = new com.google.protobuf.AbstractParser<ClientIssue>() {
            @java.lang.Override
            public ClientIssue parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new ClientIssue(input, extensionRegistry);
            }
        };
        private static final long serialVersionUID = 0L;
        // @@protoc_insertion_point(class_scope:ClientIssue)
        private static final Playlist4Issues.ClientIssue DEFAULT_INSTANCE;

        static {
            DEFAULT_INSTANCE = new Playlist4Issues.ClientIssue();
        }

        private int bitField0_;
        private int level_;
        private int code_;
        private int repeatCount_;
        private byte memoizedIsInitialized = -1;

        // Use ClientIssue.newBuilder() to construct.
        private ClientIssue(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }

        private ClientIssue() {
            level_ = 0;
            code_ = 0;
            repeatCount_ = 0;
        }

        private ClientIssue(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            if (extensionRegistry == null) {
                throw new java.lang.NullPointerException();
            }
            int mutable_bitField0_ = 0;
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                    com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        case 8: {
                            int rawValue = input.readEnum();
                            @SuppressWarnings("deprecation")
                            Playlist4Issues.ClientIssue.Level value = Playlist4Issues.ClientIssue.Level.valueOf(rawValue);
                            if (value == null) {
                                unknownFields.mergeVarintField(1, rawValue);
                            } else {
                                bitField0_ |= 0x00000001;
                                level_ = rawValue;
                            }
                            break;
                        }
                        case 16: {
                            int rawValue = input.readEnum();
                            @SuppressWarnings("deprecation")
                            Playlist4Issues.ClientIssue.Code value = Playlist4Issues.ClientIssue.Code.valueOf(rawValue);
                            if (value == null) {
                                unknownFields.mergeVarintField(2, rawValue);
                            } else {
                                bitField0_ |= 0x00000002;
                                code_ = rawValue;
                            }
                            break;
                        }
                        case 24: {
                            bitField0_ |= 0x00000004;
                            repeatCount_ = input.readInt32();
                            break;
                        }
                        default: {
                            if (!parseUnknownField(
                                    input, unknownFields, extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return Playlist4Issues.internal_static_ClientIssue_descriptor;
        }

        public static Playlist4Issues.ClientIssue parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static Playlist4Issues.ClientIssue parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static Playlist4Issues.ClientIssue parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static Playlist4Issues.ClientIssue parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static Playlist4Issues.ClientIssue parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static Playlist4Issues.ClientIssue parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static Playlist4Issues.ClientIssue parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static Playlist4Issues.ClientIssue parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static Playlist4Issues.ClientIssue parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }

        public static Playlist4Issues.ClientIssue parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static Playlist4Issues.ClientIssue parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static Playlist4Issues.ClientIssue parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(Playlist4Issues.ClientIssue prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        public static Playlist4Issues.ClientIssue getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        public static com.google.protobuf.Parser<ClientIssue> parser() {
            return PARSER;
        }

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return this.unknownFields;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return Playlist4Issues.internal_static_ClientIssue_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            Playlist4Issues.ClientIssue.class, Playlist4Issues.ClientIssue.Builder.class);
        }

        /**
         * <code>optional .ClientIssue.Level level = 1;</code>
         */
        public boolean hasLevel() {
            return ((bitField0_ & 0x00000001) == 0x00000001);
        }

        /**
         * <code>optional .ClientIssue.Level level = 1;</code>
         */
        public Playlist4Issues.ClientIssue.Level getLevel() {
            @SuppressWarnings("deprecation")
            Playlist4Issues.ClientIssue.Level result = Playlist4Issues.ClientIssue.Level.valueOf(level_);
            return result == null ? Playlist4Issues.ClientIssue.Level.LEVEL_UNKNOWN : result;
        }

        /**
         * <code>optional .ClientIssue.Code code = 2;</code>
         */
        public boolean hasCode() {
            return ((bitField0_ & 0x00000002) == 0x00000002);
        }

        /**
         * <code>optional .ClientIssue.Code code = 2;</code>
         */
        public Playlist4Issues.ClientIssue.Code getCode() {
            @SuppressWarnings("deprecation")
            Playlist4Issues.ClientIssue.Code result = Playlist4Issues.ClientIssue.Code.valueOf(code_);
            return result == null ? Playlist4Issues.ClientIssue.Code.CODE_UNKNOWN : result;
        }

        /**
         * <code>optional int32 repeatCount = 3;</code>
         */
        public boolean hasRepeatCount() {
            return ((bitField0_ & 0x00000004) == 0x00000004);
        }

        /**
         * <code>optional int32 repeatCount = 3;</code>
         */
        public int getRepeatCount() {
            return repeatCount_;
        }

        @java.lang.Override
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        @java.lang.Override
        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                output.writeEnum(1, level_);
            }
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
                output.writeEnum(2, code_);
            }
            if (((bitField0_ & 0x00000004) == 0x00000004)) {
                output.writeInt32(3, repeatCount_);
            }
            unknownFields.writeTo(output);
        }

        @java.lang.Override
        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeEnumSize(1, level_);
            }
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeEnumSize(2, code_);
            }
            if (((bitField0_ & 0x00000004) == 0x00000004)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt32Size(3, repeatCount_);
            }
            size += unknownFields.getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof Playlist4Issues.ClientIssue)) {
                return super.equals(obj);
            }
            Playlist4Issues.ClientIssue other = (Playlist4Issues.ClientIssue) obj;

            boolean result = true;
            result = result && (hasLevel() == other.hasLevel());
            if (hasLevel()) {
                result = result && level_ == other.level_;
            }
            result = result && (hasCode() == other.hasCode());
            if (hasCode()) {
                result = result && code_ == other.code_;
            }
            result = result && (hasRepeatCount() == other.hasRepeatCount());
            if (hasRepeatCount()) {
                result = result && (getRepeatCount()
                        == other.getRepeatCount());
            }
            result = result && unknownFields.equals(other.unknownFields);
            return result;
        }

        @java.lang.Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            if (hasLevel()) {
                hash = (37 * hash) + LEVEL_FIELD_NUMBER;
                hash = (53 * hash) + level_;
            }
            if (hasCode()) {
                hash = (37 * hash) + CODE_FIELD_NUMBER;
                hash = (53 * hash) + code_;
            }
            if (hasRepeatCount()) {
                hash = (37 * hash) + REPEATCOUNT_FIELD_NUMBER;
                hash = (53 * hash) + getRepeatCount();
            }
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        @java.lang.Override
        public Builder newBuilderForType() {
            return newBuilder();
        }

        @java.lang.Override
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<ClientIssue> getParserForType() {
            return PARSER;
        }

        @java.lang.Override
        public Playlist4Issues.ClientIssue getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

        /**
         * Protobuf enum {@code ClientIssue.Level}
         */
        public enum Level
                implements com.google.protobuf.ProtocolMessageEnum {
            /**
             * <code>LEVEL_UNKNOWN = 0;</code>
             */
            LEVEL_UNKNOWN(0),
            /**
             * <code>LEVEL_DEBUG = 1;</code>
             */
            LEVEL_DEBUG(1),
            /**
             * <code>LEVEL_INFO = 2;</code>
             */
            LEVEL_INFO(2),
            /**
             * <code>LEVEL_NOTICE = 3;</code>
             */
            LEVEL_NOTICE(3),
            /**
             * <code>LEVEL_WARNING = 4;</code>
             */
            LEVEL_WARNING(4),
            /**
             * <code>LEVEL_ERROR = 5;</code>
             */
            LEVEL_ERROR(5),;

            /**
             * <code>LEVEL_UNKNOWN = 0;</code>
             */
            public static final int LEVEL_UNKNOWN_VALUE = 0;
            /**
             * <code>LEVEL_DEBUG = 1;</code>
             */
            public static final int LEVEL_DEBUG_VALUE = 1;
            /**
             * <code>LEVEL_INFO = 2;</code>
             */
            public static final int LEVEL_INFO_VALUE = 2;
            /**
             * <code>LEVEL_NOTICE = 3;</code>
             */
            public static final int LEVEL_NOTICE_VALUE = 3;
            /**
             * <code>LEVEL_WARNING = 4;</code>
             */
            public static final int LEVEL_WARNING_VALUE = 4;
            /**
             * <code>LEVEL_ERROR = 5;</code>
             */
            public static final int LEVEL_ERROR_VALUE = 5;
            private static final com.google.protobuf.Internal.EnumLiteMap<
                    Level> internalValueMap =
                    new com.google.protobuf.Internal.EnumLiteMap<Level>() {
                        public Level findValueByNumber(int number) {
                            return Level.forNumber(number);
                        }
                    };
            private static final Level[] VALUES = values();
            private final int value;

            private Level(int value) {
                this.value = value;
            }

            /**
             * @deprecated Use {@link #forNumber(int)} instead.
             */
            @java.lang.Deprecated
            public static Level valueOf(int value) {
                return forNumber(value);
            }

            public static Level forNumber(int value) {
                switch (value) {
                    case 0:
                        return LEVEL_UNKNOWN;
                    case 1:
                        return LEVEL_DEBUG;
                    case 2:
                        return LEVEL_INFO;
                    case 3:
                        return LEVEL_NOTICE;
                    case 4:
                        return LEVEL_WARNING;
                    case 5:
                        return LEVEL_ERROR;
                    default:
                        return null;
                }
            }

            public static com.google.protobuf.Internal.EnumLiteMap<Level>
            internalGetValueMap() {
                return internalValueMap;
            }

            public static final com.google.protobuf.Descriptors.EnumDescriptor
            getDescriptor() {
                return Playlist4Issues.ClientIssue.getDescriptor().getEnumTypes().get(0);
            }

            public static Level valueOf(
                    com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
                if (desc.getType() != getDescriptor()) {
                    throw new java.lang.IllegalArgumentException(
                            "EnumValueDescriptor is not for this type.");
                }
                return VALUES[desc.getIndex()];
            }

            public final int getNumber() {
                return value;
            }

            public final com.google.protobuf.Descriptors.EnumValueDescriptor
            getValueDescriptor() {
                return getDescriptor().getValues().get(ordinal());
            }

            public final com.google.protobuf.Descriptors.EnumDescriptor
            getDescriptorForType() {
                return getDescriptor();
            }

            // @@protoc_insertion_point(enum_scope:ClientIssue.Level)
        }

        /**
         * Protobuf enum {@code ClientIssue.Code}
         */
        public enum Code
                implements com.google.protobuf.ProtocolMessageEnum {
            /**
             * <code>CODE_UNKNOWN = 0;</code>
             */
            CODE_UNKNOWN(0),
            /**
             * <code>CODE_INDEX_OUT_OF_BOUNDS = 1;</code>
             */
            CODE_INDEX_OUT_OF_BOUNDS(1),
            /**
             * <code>CODE_VERSION_MISMATCH = 2;</code>
             */
            CODE_VERSION_MISMATCH(2),
            /**
             * <code>CODE_CACHED_CHANGE = 3;</code>
             */
            CODE_CACHED_CHANGE(3),
            /**
             * <code>CODE_OFFLINE_CHANGE = 4;</code>
             */
            CODE_OFFLINE_CHANGE(4),
            /**
             * <code>CODE_CONCURRENT_CHANGE = 5;</code>
             */
            CODE_CONCURRENT_CHANGE(5),;

            /**
             * <code>CODE_UNKNOWN = 0;</code>
             */
            public static final int CODE_UNKNOWN_VALUE = 0;
            /**
             * <code>CODE_INDEX_OUT_OF_BOUNDS = 1;</code>
             */
            public static final int CODE_INDEX_OUT_OF_BOUNDS_VALUE = 1;
            /**
             * <code>CODE_VERSION_MISMATCH = 2;</code>
             */
            public static final int CODE_VERSION_MISMATCH_VALUE = 2;
            /**
             * <code>CODE_CACHED_CHANGE = 3;</code>
             */
            public static final int CODE_CACHED_CHANGE_VALUE = 3;
            /**
             * <code>CODE_OFFLINE_CHANGE = 4;</code>
             */
            public static final int CODE_OFFLINE_CHANGE_VALUE = 4;
            /**
             * <code>CODE_CONCURRENT_CHANGE = 5;</code>
             */
            public static final int CODE_CONCURRENT_CHANGE_VALUE = 5;
            private static final com.google.protobuf.Internal.EnumLiteMap<
                    Code> internalValueMap =
                    new com.google.protobuf.Internal.EnumLiteMap<Code>() {
                        public Code findValueByNumber(int number) {
                            return Code.forNumber(number);
                        }
                    };
            private static final Code[] VALUES = values();
            private final int value;

            private Code(int value) {
                this.value = value;
            }

            /**
             * @deprecated Use {@link #forNumber(int)} instead.
             */
            @java.lang.Deprecated
            public static Code valueOf(int value) {
                return forNumber(value);
            }

            public static Code forNumber(int value) {
                switch (value) {
                    case 0:
                        return CODE_UNKNOWN;
                    case 1:
                        return CODE_INDEX_OUT_OF_BOUNDS;
                    case 2:
                        return CODE_VERSION_MISMATCH;
                    case 3:
                        return CODE_CACHED_CHANGE;
                    case 4:
                        return CODE_OFFLINE_CHANGE;
                    case 5:
                        return CODE_CONCURRENT_CHANGE;
                    default:
                        return null;
                }
            }

            public static com.google.protobuf.Internal.EnumLiteMap<Code>
            internalGetValueMap() {
                return internalValueMap;
            }

            public static final com.google.protobuf.Descriptors.EnumDescriptor
            getDescriptor() {
                return Playlist4Issues.ClientIssue.getDescriptor().getEnumTypes().get(1);
            }

            public static Code valueOf(
                    com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
                if (desc.getType() != getDescriptor()) {
                    throw new java.lang.IllegalArgumentException(
                            "EnumValueDescriptor is not for this type.");
                }
                return VALUES[desc.getIndex()];
            }

            public final int getNumber() {
                return value;
            }

            public final com.google.protobuf.Descriptors.EnumValueDescriptor
            getValueDescriptor() {
                return getDescriptor().getValues().get(ordinal());
            }

            public final com.google.protobuf.Descriptors.EnumDescriptor
            getDescriptorForType() {
                return getDescriptor();
            }

            // @@protoc_insertion_point(enum_scope:ClientIssue.Code)
        }

        /**
         * Protobuf type {@code ClientIssue}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:ClientIssue)
                Playlist4Issues.ClientIssueOrBuilder {
            private int bitField0_;
            private int level_ = 0;
            private int code_ = 0;
            private int repeatCount_;

            // Construct using Playlist4Issues.ClientIssue.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return Playlist4Issues.internal_static_ClientIssue_descriptor;
            }

            @java.lang.Override
            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return Playlist4Issues.internal_static_ClientIssue_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                Playlist4Issues.ClientIssue.class, Playlist4Issues.ClientIssue.Builder.class);
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                }
            }

            @java.lang.Override
            public Builder clear() {
                super.clear();
                level_ = 0;
                bitField0_ = (bitField0_ & ~0x00000001);
                code_ = 0;
                bitField0_ = (bitField0_ & ~0x00000002);
                repeatCount_ = 0;
                bitField0_ = (bitField0_ & ~0x00000004);
                return this;
            }

            @java.lang.Override
            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return Playlist4Issues.internal_static_ClientIssue_descriptor;
            }

            @java.lang.Override
            public Playlist4Issues.ClientIssue getDefaultInstanceForType() {
                return Playlist4Issues.ClientIssue.getDefaultInstance();
            }

            @java.lang.Override
            public Playlist4Issues.ClientIssue build() {
                Playlist4Issues.ClientIssue result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @java.lang.Override
            public Playlist4Issues.ClientIssue buildPartial() {
                Playlist4Issues.ClientIssue result = new Playlist4Issues.ClientIssue(this);
                int from_bitField0_ = bitField0_;
                int to_bitField0_ = 0;
                if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
                    to_bitField0_ |= 0x00000001;
                }
                result.level_ = level_;
                if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
                    to_bitField0_ |= 0x00000002;
                }
                result.code_ = code_;
                if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
                    to_bitField0_ |= 0x00000004;
                }
                result.repeatCount_ = repeatCount_;
                result.bitField0_ = to_bitField0_;
                onBuilt();
                return result;
            }

            @java.lang.Override
            public Builder clone() {
                return (Builder) super.clone();
            }

            @java.lang.Override
            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return (Builder) super.setField(field, value);
            }

            @java.lang.Override
            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return (Builder) super.clearField(field);
            }

            @java.lang.Override
            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return (Builder) super.clearOneof(oneof);
            }

            @java.lang.Override
            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, java.lang.Object value) {
                return (Builder) super.setRepeatedField(field, index, value);
            }

            @java.lang.Override
            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return (Builder) super.addRepeatedField(field, value);
            }

            @java.lang.Override
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof Playlist4Issues.ClientIssue) {
                    return mergeFrom((Playlist4Issues.ClientIssue) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(Playlist4Issues.ClientIssue other) {
                if (other == Playlist4Issues.ClientIssue.getDefaultInstance()) return this;
                if (other.hasLevel()) {
                    setLevel(other.getLevel());
                }
                if (other.hasCode()) {
                    setCode(other.getCode());
                }
                if (other.hasRepeatCount()) {
                    setRepeatCount(other.getRepeatCount());
                }
                this.mergeUnknownFields(other.unknownFields);
                onChanged();
                return this;
            }

            @java.lang.Override
            public final boolean isInitialized() {
                return true;
            }

            @java.lang.Override
            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                Playlist4Issues.ClientIssue parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (Playlist4Issues.ClientIssue) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            /**
             * <code>optional .ClientIssue.Level level = 1;</code>
             */
            public boolean hasLevel() {
                return ((bitField0_ & 0x00000001) == 0x00000001);
            }

            /**
             * <code>optional .ClientIssue.Level level = 1;</code>
             */
            public Playlist4Issues.ClientIssue.Level getLevel() {
                @SuppressWarnings("deprecation")
                Playlist4Issues.ClientIssue.Level result = Playlist4Issues.ClientIssue.Level.valueOf(level_);
                return result == null ? Playlist4Issues.ClientIssue.Level.LEVEL_UNKNOWN : result;
            }

            /**
             * <code>optional .ClientIssue.Level level = 1;</code>
             */
            public Builder setLevel(Playlist4Issues.ClientIssue.Level value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000001;
                level_ = value.getNumber();
                onChanged();
                return this;
            }

            /**
             * <code>optional .ClientIssue.Level level = 1;</code>
             */
            public Builder clearLevel() {
                bitField0_ = (bitField0_ & ~0x00000001);
                level_ = 0;
                onChanged();
                return this;
            }

            /**
             * <code>optional .ClientIssue.Code code = 2;</code>
             */
            public boolean hasCode() {
                return ((bitField0_ & 0x00000002) == 0x00000002);
            }

            /**
             * <code>optional .ClientIssue.Code code = 2;</code>
             */
            public Playlist4Issues.ClientIssue.Code getCode() {
                @SuppressWarnings("deprecation")
                Playlist4Issues.ClientIssue.Code result = Playlist4Issues.ClientIssue.Code.valueOf(code_);
                return result == null ? Playlist4Issues.ClientIssue.Code.CODE_UNKNOWN : result;
            }

            /**
             * <code>optional .ClientIssue.Code code = 2;</code>
             */
            public Builder setCode(Playlist4Issues.ClientIssue.Code value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000002;
                code_ = value.getNumber();
                onChanged();
                return this;
            }

            /**
             * <code>optional .ClientIssue.Code code = 2;</code>
             */
            public Builder clearCode() {
                bitField0_ = (bitField0_ & ~0x00000002);
                code_ = 0;
                onChanged();
                return this;
            }

            /**
             * <code>optional int32 repeatCount = 3;</code>
             */
            public boolean hasRepeatCount() {
                return ((bitField0_ & 0x00000004) == 0x00000004);
            }

            /**
             * <code>optional int32 repeatCount = 3;</code>
             */
            public int getRepeatCount() {
                return repeatCount_;
            }

            /**
             * <code>optional int32 repeatCount = 3;</code>
             */
            public Builder setRepeatCount(int value) {
                bitField0_ |= 0x00000004;
                repeatCount_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional int32 repeatCount = 3;</code>
             */
            public Builder clearRepeatCount() {
                bitField0_ = (bitField0_ & ~0x00000004);
                repeatCount_ = 0;
                onChanged();
                return this;
            }

            @java.lang.Override
            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.setUnknownFields(unknownFields);
            }

            @java.lang.Override
            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.mergeUnknownFields(unknownFields);
            }


            // @@protoc_insertion_point(builder_scope:ClientIssue)
        }

    }

    /**
     * Protobuf type {@code ClientResolveAction}
     */
    public static final class ClientResolveAction extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:ClientResolveAction)
            ClientResolveActionOrBuilder {
        public static final int CODE_FIELD_NUMBER = 1;
        public static final int INITIATOR_FIELD_NUMBER = 2;
        @java.lang.Deprecated
        public static final com.google.protobuf.Parser<ClientResolveAction>
                PARSER = new com.google.protobuf.AbstractParser<ClientResolveAction>() {
            @java.lang.Override
            public ClientResolveAction parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new ClientResolveAction(input, extensionRegistry);
            }
        };
        private static final long serialVersionUID = 0L;
        // @@protoc_insertion_point(class_scope:ClientResolveAction)
        private static final Playlist4Issues.ClientResolveAction DEFAULT_INSTANCE;

        static {
            DEFAULT_INSTANCE = new Playlist4Issues.ClientResolveAction();
        }

        private int bitField0_;
        private int code_;
        private int initiator_;
        private byte memoizedIsInitialized = -1;

        // Use ClientResolveAction.newBuilder() to construct.
        private ClientResolveAction(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }

        private ClientResolveAction() {
            code_ = 0;
            initiator_ = 0;
        }

        private ClientResolveAction(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            if (extensionRegistry == null) {
                throw new java.lang.NullPointerException();
            }
            int mutable_bitField0_ = 0;
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                    com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        case 8: {
                            int rawValue = input.readEnum();
                            @SuppressWarnings("deprecation")
                            Playlist4Issues.ClientResolveAction.Code value = Playlist4Issues.ClientResolveAction.Code.valueOf(rawValue);
                            if (value == null) {
                                unknownFields.mergeVarintField(1, rawValue);
                            } else {
                                bitField0_ |= 0x00000001;
                                code_ = rawValue;
                            }
                            break;
                        }
                        case 16: {
                            int rawValue = input.readEnum();
                            @SuppressWarnings("deprecation")
                            Playlist4Issues.ClientResolveAction.Initiator value = Playlist4Issues.ClientResolveAction.Initiator.valueOf(rawValue);
                            if (value == null) {
                                unknownFields.mergeVarintField(2, rawValue);
                            } else {
                                bitField0_ |= 0x00000002;
                                initiator_ = rawValue;
                            }
                            break;
                        }
                        default: {
                            if (!parseUnknownField(
                                    input, unknownFields, extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return Playlist4Issues.internal_static_ClientResolveAction_descriptor;
        }

        public static Playlist4Issues.ClientResolveAction parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static Playlist4Issues.ClientResolveAction parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static Playlist4Issues.ClientResolveAction parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static Playlist4Issues.ClientResolveAction parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static Playlist4Issues.ClientResolveAction parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static Playlist4Issues.ClientResolveAction parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static Playlist4Issues.ClientResolveAction parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static Playlist4Issues.ClientResolveAction parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static Playlist4Issues.ClientResolveAction parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }

        public static Playlist4Issues.ClientResolveAction parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static Playlist4Issues.ClientResolveAction parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static Playlist4Issues.ClientResolveAction parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(Playlist4Issues.ClientResolveAction prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        public static Playlist4Issues.ClientResolveAction getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        public static com.google.protobuf.Parser<ClientResolveAction> parser() {
            return PARSER;
        }

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return this.unknownFields;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return Playlist4Issues.internal_static_ClientResolveAction_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            Playlist4Issues.ClientResolveAction.class, Playlist4Issues.ClientResolveAction.Builder.class);
        }

        /**
         * <code>optional .ClientResolveAction.Code code = 1;</code>
         */
        public boolean hasCode() {
            return ((bitField0_ & 0x00000001) == 0x00000001);
        }

        /**
         * <code>optional .ClientResolveAction.Code code = 1;</code>
         */
        public Playlist4Issues.ClientResolveAction.Code getCode() {
            @SuppressWarnings("deprecation")
            Playlist4Issues.ClientResolveAction.Code result = Playlist4Issues.ClientResolveAction.Code.valueOf(code_);
            return result == null ? Playlist4Issues.ClientResolveAction.Code.CODE_UNKNOWN : result;
        }

        /**
         * <code>optional .ClientResolveAction.Initiator initiator = 2;</code>
         */
        public boolean hasInitiator() {
            return ((bitField0_ & 0x00000002) == 0x00000002);
        }

        /**
         * <code>optional .ClientResolveAction.Initiator initiator = 2;</code>
         */
        public Playlist4Issues.ClientResolveAction.Initiator getInitiator() {
            @SuppressWarnings("deprecation")
            Playlist4Issues.ClientResolveAction.Initiator result = Playlist4Issues.ClientResolveAction.Initiator.valueOf(initiator_);
            return result == null ? Playlist4Issues.ClientResolveAction.Initiator.INITIATOR_UNKNOWN : result;
        }

        @java.lang.Override
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        @java.lang.Override
        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                output.writeEnum(1, code_);
            }
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
                output.writeEnum(2, initiator_);
            }
            unknownFields.writeTo(output);
        }

        @java.lang.Override
        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeEnumSize(1, code_);
            }
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeEnumSize(2, initiator_);
            }
            size += unknownFields.getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof Playlist4Issues.ClientResolveAction)) {
                return super.equals(obj);
            }
            Playlist4Issues.ClientResolveAction other = (Playlist4Issues.ClientResolveAction) obj;

            boolean result = true;
            result = result && (hasCode() == other.hasCode());
            if (hasCode()) {
                result = result && code_ == other.code_;
            }
            result = result && (hasInitiator() == other.hasInitiator());
            if (hasInitiator()) {
                result = result && initiator_ == other.initiator_;
            }
            result = result && unknownFields.equals(other.unknownFields);
            return result;
        }

        @java.lang.Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            if (hasCode()) {
                hash = (37 * hash) + CODE_FIELD_NUMBER;
                hash = (53 * hash) + code_;
            }
            if (hasInitiator()) {
                hash = (37 * hash) + INITIATOR_FIELD_NUMBER;
                hash = (53 * hash) + initiator_;
            }
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        @java.lang.Override
        public Builder newBuilderForType() {
            return newBuilder();
        }

        @java.lang.Override
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<ClientResolveAction> getParserForType() {
            return PARSER;
        }

        @java.lang.Override
        public Playlist4Issues.ClientResolveAction getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

        /**
         * Protobuf enum {@code ClientResolveAction.Code}
         */
        public enum Code
                implements com.google.protobuf.ProtocolMessageEnum {
            /**
             * <code>CODE_UNKNOWN = 0;</code>
             */
            CODE_UNKNOWN(0),
            /**
             * <code>CODE_NO_ACTION = 1;</code>
             */
            CODE_NO_ACTION(1),
            /**
             * <code>CODE_RETRY = 2;</code>
             */
            CODE_RETRY(2),
            /**
             * <code>CODE_RELOAD = 3;</code>
             */
            CODE_RELOAD(3),
            /**
             * <code>CODE_DISCARD_LOCAL_CHANGES = 4;</code>
             */
            CODE_DISCARD_LOCAL_CHANGES(4),
            /**
             * <code>CODE_SEND_DUMP = 5;</code>
             */
            CODE_SEND_DUMP(5),
            /**
             * <code>CODE_DISPLAY_ERROR_MESSAGE = 6;</code>
             */
            CODE_DISPLAY_ERROR_MESSAGE(6),;

            /**
             * <code>CODE_UNKNOWN = 0;</code>
             */
            public static final int CODE_UNKNOWN_VALUE = 0;
            /**
             * <code>CODE_NO_ACTION = 1;</code>
             */
            public static final int CODE_NO_ACTION_VALUE = 1;
            /**
             * <code>CODE_RETRY = 2;</code>
             */
            public static final int CODE_RETRY_VALUE = 2;
            /**
             * <code>CODE_RELOAD = 3;</code>
             */
            public static final int CODE_RELOAD_VALUE = 3;
            /**
             * <code>CODE_DISCARD_LOCAL_CHANGES = 4;</code>
             */
            public static final int CODE_DISCARD_LOCAL_CHANGES_VALUE = 4;
            /**
             * <code>CODE_SEND_DUMP = 5;</code>
             */
            public static final int CODE_SEND_DUMP_VALUE = 5;
            /**
             * <code>CODE_DISPLAY_ERROR_MESSAGE = 6;</code>
             */
            public static final int CODE_DISPLAY_ERROR_MESSAGE_VALUE = 6;
            private static final com.google.protobuf.Internal.EnumLiteMap<
                    Code> internalValueMap =
                    new com.google.protobuf.Internal.EnumLiteMap<Code>() {
                        public Code findValueByNumber(int number) {
                            return Code.forNumber(number);
                        }
                    };
            private static final Code[] VALUES = values();
            private final int value;

            private Code(int value) {
                this.value = value;
            }

            /**
             * @deprecated Use {@link #forNumber(int)} instead.
             */
            @java.lang.Deprecated
            public static Code valueOf(int value) {
                return forNumber(value);
            }

            public static Code forNumber(int value) {
                switch (value) {
                    case 0:
                        return CODE_UNKNOWN;
                    case 1:
                        return CODE_NO_ACTION;
                    case 2:
                        return CODE_RETRY;
                    case 3:
                        return CODE_RELOAD;
                    case 4:
                        return CODE_DISCARD_LOCAL_CHANGES;
                    case 5:
                        return CODE_SEND_DUMP;
                    case 6:
                        return CODE_DISPLAY_ERROR_MESSAGE;
                    default:
                        return null;
                }
            }

            public static com.google.protobuf.Internal.EnumLiteMap<Code>
            internalGetValueMap() {
                return internalValueMap;
            }

            public static final com.google.protobuf.Descriptors.EnumDescriptor
            getDescriptor() {
                return Playlist4Issues.ClientResolveAction.getDescriptor().getEnumTypes().get(0);
            }

            public static Code valueOf(
                    com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
                if (desc.getType() != getDescriptor()) {
                    throw new java.lang.IllegalArgumentException(
                            "EnumValueDescriptor is not for this type.");
                }
                return VALUES[desc.getIndex()];
            }

            public final int getNumber() {
                return value;
            }

            public final com.google.protobuf.Descriptors.EnumValueDescriptor
            getValueDescriptor() {
                return getDescriptor().getValues().get(ordinal());
            }

            public final com.google.protobuf.Descriptors.EnumDescriptor
            getDescriptorForType() {
                return getDescriptor();
            }

            // @@protoc_insertion_point(enum_scope:ClientResolveAction.Code)
        }

        /**
         * Protobuf enum {@code ClientResolveAction.Initiator}
         */
        public enum Initiator
                implements com.google.protobuf.ProtocolMessageEnum {
            /**
             * <code>INITIATOR_UNKNOWN = 0;</code>
             */
            INITIATOR_UNKNOWN(0),
            /**
             * <code>INITIATOR_SERVER = 1;</code>
             */
            INITIATOR_SERVER(1),
            /**
             * <code>INITIATOR_CLIENT = 2;</code>
             */
            INITIATOR_CLIENT(2),;

            /**
             * <code>INITIATOR_UNKNOWN = 0;</code>
             */
            public static final int INITIATOR_UNKNOWN_VALUE = 0;
            /**
             * <code>INITIATOR_SERVER = 1;</code>
             */
            public static final int INITIATOR_SERVER_VALUE = 1;
            /**
             * <code>INITIATOR_CLIENT = 2;</code>
             */
            public static final int INITIATOR_CLIENT_VALUE = 2;
            private static final com.google.protobuf.Internal.EnumLiteMap<
                    Initiator> internalValueMap =
                    new com.google.protobuf.Internal.EnumLiteMap<Initiator>() {
                        public Initiator findValueByNumber(int number) {
                            return Initiator.forNumber(number);
                        }
                    };
            private static final Initiator[] VALUES = values();
            private final int value;

            private Initiator(int value) {
                this.value = value;
            }

            /**
             * @deprecated Use {@link #forNumber(int)} instead.
             */
            @java.lang.Deprecated
            public static Initiator valueOf(int value) {
                return forNumber(value);
            }

            public static Initiator forNumber(int value) {
                switch (value) {
                    case 0:
                        return INITIATOR_UNKNOWN;
                    case 1:
                        return INITIATOR_SERVER;
                    case 2:
                        return INITIATOR_CLIENT;
                    default:
                        return null;
                }
            }

            public static com.google.protobuf.Internal.EnumLiteMap<Initiator>
            internalGetValueMap() {
                return internalValueMap;
            }

            public static final com.google.protobuf.Descriptors.EnumDescriptor
            getDescriptor() {
                return Playlist4Issues.ClientResolveAction.getDescriptor().getEnumTypes().get(1);
            }

            public static Initiator valueOf(
                    com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
                if (desc.getType() != getDescriptor()) {
                    throw new java.lang.IllegalArgumentException(
                            "EnumValueDescriptor is not for this type.");
                }
                return VALUES[desc.getIndex()];
            }

            public final int getNumber() {
                return value;
            }

            public final com.google.protobuf.Descriptors.EnumValueDescriptor
            getValueDescriptor() {
                return getDescriptor().getValues().get(ordinal());
            }

            public final com.google.protobuf.Descriptors.EnumDescriptor
            getDescriptorForType() {
                return getDescriptor();
            }

            // @@protoc_insertion_point(enum_scope:ClientResolveAction.Initiator)
        }

        /**
         * Protobuf type {@code ClientResolveAction}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:ClientResolveAction)
                Playlist4Issues.ClientResolveActionOrBuilder {
            private int bitField0_;
            private int code_ = 0;
            private int initiator_ = 0;

            // Construct using Playlist4Issues.ClientResolveAction.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return Playlist4Issues.internal_static_ClientResolveAction_descriptor;
            }

            @java.lang.Override
            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return Playlist4Issues.internal_static_ClientResolveAction_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                Playlist4Issues.ClientResolveAction.class, Playlist4Issues.ClientResolveAction.Builder.class);
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                }
            }

            @java.lang.Override
            public Builder clear() {
                super.clear();
                code_ = 0;
                bitField0_ = (bitField0_ & ~0x00000001);
                initiator_ = 0;
                bitField0_ = (bitField0_ & ~0x00000002);
                return this;
            }

            @java.lang.Override
            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return Playlist4Issues.internal_static_ClientResolveAction_descriptor;
            }

            @java.lang.Override
            public Playlist4Issues.ClientResolveAction getDefaultInstanceForType() {
                return Playlist4Issues.ClientResolveAction.getDefaultInstance();
            }

            @java.lang.Override
            public Playlist4Issues.ClientResolveAction build() {
                Playlist4Issues.ClientResolveAction result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @java.lang.Override
            public Playlist4Issues.ClientResolveAction buildPartial() {
                Playlist4Issues.ClientResolveAction result = new Playlist4Issues.ClientResolveAction(this);
                int from_bitField0_ = bitField0_;
                int to_bitField0_ = 0;
                if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
                    to_bitField0_ |= 0x00000001;
                }
                result.code_ = code_;
                if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
                    to_bitField0_ |= 0x00000002;
                }
                result.initiator_ = initiator_;
                result.bitField0_ = to_bitField0_;
                onBuilt();
                return result;
            }

            @java.lang.Override
            public Builder clone() {
                return (Builder) super.clone();
            }

            @java.lang.Override
            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return (Builder) super.setField(field, value);
            }

            @java.lang.Override
            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return (Builder) super.clearField(field);
            }

            @java.lang.Override
            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return (Builder) super.clearOneof(oneof);
            }

            @java.lang.Override
            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, java.lang.Object value) {
                return (Builder) super.setRepeatedField(field, index, value);
            }

            @java.lang.Override
            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return (Builder) super.addRepeatedField(field, value);
            }

            @java.lang.Override
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof Playlist4Issues.ClientResolveAction) {
                    return mergeFrom((Playlist4Issues.ClientResolveAction) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(Playlist4Issues.ClientResolveAction other) {
                if (other == Playlist4Issues.ClientResolveAction.getDefaultInstance()) return this;
                if (other.hasCode()) {
                    setCode(other.getCode());
                }
                if (other.hasInitiator()) {
                    setInitiator(other.getInitiator());
                }
                this.mergeUnknownFields(other.unknownFields);
                onChanged();
                return this;
            }

            @java.lang.Override
            public final boolean isInitialized() {
                return true;
            }

            @java.lang.Override
            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                Playlist4Issues.ClientResolveAction parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (Playlist4Issues.ClientResolveAction) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            /**
             * <code>optional .ClientResolveAction.Code code = 1;</code>
             */
            public boolean hasCode() {
                return ((bitField0_ & 0x00000001) == 0x00000001);
            }

            /**
             * <code>optional .ClientResolveAction.Code code = 1;</code>
             */
            public Playlist4Issues.ClientResolveAction.Code getCode() {
                @SuppressWarnings("deprecation")
                Playlist4Issues.ClientResolveAction.Code result = Playlist4Issues.ClientResolveAction.Code.valueOf(code_);
                return result == null ? Playlist4Issues.ClientResolveAction.Code.CODE_UNKNOWN : result;
            }

            /**
             * <code>optional .ClientResolveAction.Code code = 1;</code>
             */
            public Builder setCode(Playlist4Issues.ClientResolveAction.Code value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000001;
                code_ = value.getNumber();
                onChanged();
                return this;
            }

            /**
             * <code>optional .ClientResolveAction.Code code = 1;</code>
             */
            public Builder clearCode() {
                bitField0_ = (bitField0_ & ~0x00000001);
                code_ = 0;
                onChanged();
                return this;
            }

            /**
             * <code>optional .ClientResolveAction.Initiator initiator = 2;</code>
             */
            public boolean hasInitiator() {
                return ((bitField0_ & 0x00000002) == 0x00000002);
            }

            /**
             * <code>optional .ClientResolveAction.Initiator initiator = 2;</code>
             */
            public Playlist4Issues.ClientResolveAction.Initiator getInitiator() {
                @SuppressWarnings("deprecation")
                Playlist4Issues.ClientResolveAction.Initiator result = Playlist4Issues.ClientResolveAction.Initiator.valueOf(initiator_);
                return result == null ? Playlist4Issues.ClientResolveAction.Initiator.INITIATOR_UNKNOWN : result;
            }

            /**
             * <code>optional .ClientResolveAction.Initiator initiator = 2;</code>
             */
            public Builder setInitiator(Playlist4Issues.ClientResolveAction.Initiator value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000002;
                initiator_ = value.getNumber();
                onChanged();
                return this;
            }

            /**
             * <code>optional .ClientResolveAction.Initiator initiator = 2;</code>
             */
            public Builder clearInitiator() {
                bitField0_ = (bitField0_ & ~0x00000002);
                initiator_ = 0;
                onChanged();
                return this;
            }

            @java.lang.Override
            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.setUnknownFields(unknownFields);
            }

            @java.lang.Override
            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.mergeUnknownFields(unknownFields);
            }


            // @@protoc_insertion_point(builder_scope:ClientResolveAction)
        }

    }

    // @@protoc_insertion_point(outer_class_scope)
}
